# Generated by Django 5.2.8 on 2025-12-27 18:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CrawlerKeyword",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        help_text="Search keyword or phrase", max_length=200
                    ),
                ),
                (
                    "product_types",
                    models.JSONField(
                        default=list,
                        help_text="Applicable product types: ['whiskey', 'port_wine']",
                    ),
                ),
                (
                    "search_context",
                    models.CharField(
                        choices=[
                            ("new_release", "New Release"),
                            ("review", "Review"),
                            ("competition", "Competition/Award"),
                            ("pricing", "Pricing Intelligence"),
                            ("general", "General Discovery"),
                        ],
                        default="general",
                        help_text="Context for this keyword",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "priority",
                    models.IntegerField(
                        default=5, help_text="1-10, higher = search more frequently"
                    ),
                ),
                (
                    "search_frequency_hours",
                    models.IntegerField(
                        default=168, help_text="How often to search (hours)"
                    ),
                ),
                ("last_searched_at", models.DateTimeField(blank=True, null=True)),
                ("next_search_at", models.DateTimeField(blank=True, null=True)),
                ("total_results_found", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "crawler_keywords",
                "ordering": ["-priority", "keyword"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "next_search_at"],
                        name="crawler_key_is_acti_8c2da0_idx",
                    ),
                    models.Index(
                        fields=["search_context"], name="crawler_key_search__3132bf_idx"
                    ),
                ],
                "unique_together": {("keyword", "search_context")},
            },
        ),
        migrations.CreateModel(
            name="CrawlerSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name", max_length=100, unique=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-safe identifier", max_length=100, unique=True
                    ),
                ),
                ("base_url", models.URLField(help_text="Base URL of the source")),
                (
                    "product_types",
                    models.JSONField(
                        default=list,
                        help_text="List of product types: ['whiskey', 'port_wine']",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("review", "Review Site"),
                            ("retailer", "Retailer"),
                            ("producer", "Producer Website"),
                            ("competition", "Competition/Awards"),
                            ("news", "News/Blog"),
                            ("database", "Product Database"),
                        ],
                        help_text="Type of source",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable crawling"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5, help_text="1-10, higher = more important"
                    ),
                ),
                (
                    "crawl_frequency_hours",
                    models.IntegerField(
                        default=24, help_text="How often to crawl (hours)"
                    ),
                ),
                (
                    "rate_limit_requests_per_minute",
                    models.IntegerField(
                        default=10, help_text="Max requests per minute to this domain"
                    ),
                ),
                (
                    "requires_javascript",
                    models.BooleanField(
                        default=False, help_text="Requires headless browser"
                    ),
                ),
                (
                    "requires_proxy",
                    models.BooleanField(
                        default=False, help_text="Requires proxy rotation"
                    ),
                ),
                (
                    "requires_authentication",
                    models.BooleanField(default=False, help_text="Requires login"),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True, default=dict, help_text="Custom HTTP headers"
                    ),
                ),
                (
                    "age_gate_type",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("cookie", "Cookie-based"),
                            ("click", "Click confirmation"),
                            ("form", "Form submission"),
                        ],
                        default="none",
                        help_text="Type of age gate mechanism used by this source",
                        max_length=20,
                    ),
                ),
                (
                    "age_gate_cookies",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Domain-specific cookies for age gate bypass",
                    ),
                ),
                (
                    "requires_tier3",
                    models.BooleanField(
                        default=False,
                        help_text="Marks ScrapingBee requirement (Tier 3 fetching)",
                    ),
                ),
                (
                    "discovery_method",
                    models.CharField(
                        choices=[
                            ("hub", "Hub and Spoke"),
                            ("search", "Search Discovery"),
                            ("competition", "Competition/Award"),
                            ("manual", "Manually Added"),
                        ],
                        default="manual",
                        help_text="How this source was discovered",
                        max_length=20,
                    ),
                ),
                (
                    "product_url_patterns",
                    models.JSONField(
                        default=list, help_text="Regex patterns for product URLs"
                    ),
                ),
                (
                    "pagination_pattern",
                    models.CharField(
                        blank=True,
                        help_text="URL pattern for pagination (e.g., ?page={page})",
                        max_length=200,
                    ),
                ),
                (
                    "sitemap_url",
                    models.URLField(blank=True, help_text="Sitemap URL if available"),
                ),
                (
                    "robots_txt_compliant",
                    models.BooleanField(
                        default=True, help_text="Checked robots.txt compliance"
                    ),
                ),
                (
                    "tos_compliant",
                    models.BooleanField(
                        default=True, help_text="Checked Terms of Service compliance"
                    ),
                ),
                (
                    "compliance_notes",
                    models.TextField(
                        blank=True, help_text="Notes on compliance requirements"
                    ),
                ),
                ("last_crawl_at", models.DateTimeField(blank=True, null=True)),
                ("next_crawl_at", models.DateTimeField(blank=True, null=True)),
                ("last_crawl_status", models.CharField(blank=True, max_length=20)),
                ("total_products_found", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True, help_text="Internal notes")),
            ],
            options={
                "db_table": "crawler_sources",
                "ordering": ["-priority", "name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "next_crawl_at"],
                        name="crawler_sou_is_acti_ebec6b_idx",
                    ),
                    models.Index(
                        fields=["category"], name="crawler_sou_categor_c7ad6e_idx"
                    ),
                    models.Index(
                        fields=["discovery_method"],
                        name="crawler_sou_discove_b2bfd9_idx",
                    ),
                    models.Index(
                        fields=["requires_tier3"], name="crawler_sou_require_3fd25f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CrawledArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_url",
                    models.URLField(db_index=True, max_length=2000, unique=True),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("author", models.CharField(blank=True, max_length=200)),
                ("published_date", models.DateField(blank=True, null=True)),
                (
                    "summary_bullets",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Summary bullet points extracted from article",
                    ),
                ),
                (
                    "extracted_tags",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Tags/categories extracted from article",
                    ),
                ),
                (
                    "sentiment_score",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Sentiment analysis results: {'overall': 0.8, 'products': {...}}",
                    ),
                ),
                (
                    "local_snapshot_path",
                    models.CharField(
                        blank=True,
                        help_text="Path to local HTML snapshot",
                        max_length=500,
                    ),
                ),
                (
                    "wayback_url",
                    models.URLField(
                        blank=True,
                        help_text="Wayback Machine archive URL",
                        max_length=500,
                    ),
                ),
                (
                    "is_original_live",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the original URL is still accessible",
                    ),
                ),
                (
                    "last_health_check",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time the original URL was checked for availability",
                        null=True,
                    ),
                ),
                ("discovered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawled_articles",
                        to="crawler.crawlersource",
                    ),
                ),
            ],
            options={
                "db_table": "crawled_articles",
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("pages_crawled", models.IntegerField(default=0)),
                ("products_found", models.IntegerField(default=0)),
                ("products_new", models.IntegerField(default=0)),
                ("products_updated", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("error_details", models.JSONField(blank=True, default=dict)),
                ("results_summary", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crawl_jobs",
                        to="crawler.crawlersource",
                    ),
                ),
            ],
            options={
                "db_table": "crawl_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CrawlCost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("serpapi", "SerpAPI"),
                            ("scrapingbee", "ScrapingBee"),
                            ("openai", "OpenAI"),
                        ],
                        help_text="External service used",
                        max_length=20,
                    ),
                ),
                ("cost_cents", models.IntegerField(help_text="Cost in cents (USD)")),
                (
                    "request_count",
                    models.IntegerField(default=1, help_text="Number of API requests"),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "crawl_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="costs",
                        to="crawler.crawljob",
                    ),
                ),
            ],
            options={
                "db_table": "crawl_costs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="DiscoveredProduct",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_url", models.URLField(max_length=2000)),
                (
                    "fingerprint",
                    models.CharField(
                        db_index=True, help_text="Hash for deduplication", max_length=64
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("whiskey", "Whiskey"),
                            ("port_wine", "Port Wine"),
                            ("gin", "Gin"),
                            ("rum", "Rum"),
                            ("tequila", "Tequila"),
                            ("vodka", "Vodka"),
                            ("brandy", "Brandy"),
                            ("sake", "Sake"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raw_content", models.TextField(help_text="Original HTML/text")),
                ("raw_content_hash", models.CharField(max_length=64)),
                ("extracted_data", models.JSONField(default=dict)),
                ("enriched_data", models.JSONField(default=dict)),
                ("extraction_confidence", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("duplicate", "Duplicate"),
                            ("merged", "Merged"),
                            ("skeleton", "Skeleton (needs enrichment)"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "discovery_source",
                    models.CharField(
                        choices=[
                            ("competition", "Competition/Award"),
                            ("hub_spoke", "Hub and Spoke"),
                            ("search", "Search Discovery"),
                            ("direct", "Direct Crawl"),
                        ],
                        default="direct",
                        help_text="How this product was discovered",
                        max_length=20,
                    ),
                ),
                (
                    "awards",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Competition awards data: [{'competition': 'IWSC', 'year': 2024, 'medal': 'Gold'}]",
                    ),
                ),
                (
                    "matched_product_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of matched existing product",
                        null=True,
                    ),
                ),
                ("match_confidence", models.FloatField(blank=True, null=True)),
                (
                    "discovered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=100)),
                (
                    "crawl_job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="crawler.crawljob",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovered_products",
                        to="crawler.crawlersource",
                    ),
                ),
            ],
            options={
                "db_table": "discovered_products",
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="ArticleProductMention",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mention_type",
                    models.CharField(
                        choices=[
                            ("review", "Full Review"),
                            ("mention", "Brief Mention"),
                            ("comparison", "Comparison"),
                            ("recommendation", "Recommendation"),
                            ("award", "Award/Recognition"),
                        ],
                        default="mention",
                        help_text="Type of product mention",
                        max_length=20,
                    ),
                ),
                (
                    "rating_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rating given in article (e.g., 92.5)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "rating_scale",
                    models.CharField(
                        blank=True,
                        help_text="Rating scale used (e.g., '100', 'A-F', '5 stars')",
                        max_length=20,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True, help_text="Relevant excerpt mentioning the product"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_mentions",
                        to="crawler.crawledarticle",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="article_mentions",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "db_table": "article_product_mentions",
            },
        ),
        migrations.CreateModel(
            name="CrawlError",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="URL that caused the error", max_length=2000
                    ),
                ),
                (
                    "error_type",
                    models.CharField(
                        choices=[
                            ("connection", "Connection Error"),
                            ("timeout", "Timeout"),
                            ("blocked", "Blocked/403"),
                            ("age_gate", "Age Gate Failed"),
                            ("rate_limit", "Rate Limited"),
                            ("parse", "Parse Error"),
                            ("api", "API Error"),
                            ("unknown", "Unknown Error"),
                        ],
                        help_text="Category of error",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(help_text="Error message")),
                (
                    "stack_trace",
                    models.TextField(
                        blank=True, help_text="Full stack trace if available"
                    ),
                ),
                (
                    "tier_used",
                    models.IntegerField(
                        blank=True,
                        help_text="Fetching tier used (1, 2, or 3)",
                        null=True,
                    ),
                ),
                (
                    "response_status",
                    models.IntegerField(
                        blank=True, help_text="HTTP response status code", null=True
                    ),
                ),
                (
                    "response_headers",
                    models.JSONField(
                        blank=True, default=dict, help_text="HTTP response headers"
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Whether this error has been resolved"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="errors",
                        to="crawler.crawlersource",
                    ),
                ),
            ],
            options={
                "db_table": "crawl_errors",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["source", "timestamp"],
                        name="crawl_error_source__9f50ae_idx",
                    ),
                    models.Index(
                        fields=["error_type", "timestamp"],
                        name="crawl_error_error_t_b95383_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="crawl_error_timesta_894d8b_idx"
                    ),
                    models.Index(
                        fields=["resolved"], name="crawl_error_resolve_6ddaac_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CrawledURL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=2000, unique=True)),
                (
                    "url_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("is_product_page", models.BooleanField(default=False)),
                ("was_processed", models.BooleanField(default=False)),
                ("processing_status", models.CharField(blank=True, max_length=20)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_crawled_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(blank=True, null=True)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("content_changed", models.BooleanField(default=False)),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawled_urls",
                        to="crawler.crawlersource",
                    ),
                ),
            ],
            options={
                "db_table": "crawled_urls",
                "indexes": [
                    models.Index(
                        fields=["source", "is_product_page"],
                        name="crawled_url_source__98a476_idx",
                    ),
                    models.Index(
                        fields=["was_processed"], name="crawled_url_was_pro_f06320_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="crawledarticle",
            index=models.Index(
                fields=["source", "discovered_at"],
                name="crawled_art_source__a73d21_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="crawledarticle",
            index=models.Index(
                fields=["is_original_live"], name="crawled_art_is_orig_f79ba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawledarticle",
            index=models.Index(
                fields=["published_date"], name="crawled_art_publish_f7d725_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawljob",
            index=models.Index(
                fields=["status", "created_at"], name="crawl_jobs_status_5f7b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawljob",
            index=models.Index(
                fields=["source", "created_at"], name="crawl_jobs_source__4ffd48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawlcost",
            index=models.Index(
                fields=["service", "timestamp"], name="crawl_costs_service_ef7be3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawlcost",
            index=models.Index(
                fields=["timestamp"], name="crawl_costs_timesta_d28761_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crawlcost",
            index=models.Index(
                fields=["crawl_job"], name="crawl_costs_crawl_j_cd5a3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["status", "discovered_at"], name="discovered__status_c48458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["product_type", "status"], name="discovered__product_18f75f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["fingerprint"], name="discovered__fingerp_a13270_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["discovery_source"], name="discovered__discove_55c5ca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleproductmention",
            index=models.Index(
                fields=["article"], name="article_pro_article_1c60e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleproductmention",
            index=models.Index(
                fields=["product"], name="article_pro_product_9cbfe8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="articleproductmention",
            index=models.Index(
                fields=["mention_type"], name="article_pro_mention_c8e547_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="articleproductmention",
            unique_together={("article", "product")},
        ),
    ]
