# Generated by Django 5.2.8 on 2025-12-28 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0001_initial_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawlerkeyword",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="crawlersource",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
