# Generated by Django 5.2.8 on 2025-12-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0002_fix_updated_at_for_fixtures"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlersource",
            name="auto_discover_links",
            field=models.BooleanField(
                default=True,
                help_text="Automatically discover and queue links from crawled pages",
            ),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="max_crawl_depth",
            field=models.IntegerField(
                default=3, help_text="Maximum depth to follow links (0 = base URL only)"
            ),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="max_pages",
            field=models.IntegerField(
                default=100, help_text="Maximum pages to crawl per job"
            ),
        ),
        migrations.AddField(
            model_name="crawljob",
            name="links_discovered",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="crawljob",
            name="links_queued",
            field=models.IntegerField(default=0),
        ),
    ]
