# Generated by Django 5.2.8 on 2025-12-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0003_add_auto_queue_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="best_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Current best price found",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="best_price_currency",
            field=models.CharField(
                default="USD", help_text="Currency of best price", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="best_price_retailer",
            field=models.CharField(
                blank=True, help_text="Retailer with best price", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="best_price_url",
            field=models.URLField(
                blank=True, help_text="URL to best price", max_length=2000
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="discovery_sources",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Sources that discovered this product: ['competition', 'serpapi', 'hub_crawl']",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Product images: [{url, type, source, width, height}]",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="mention_count",
            field=models.IntegerField(
                default=0, help_text="Total number of press/article mentions"
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="press_mentions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Article mentions: [{url, title, source, date, snippet, mention_type}]",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="price_history",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Historical prices: [{price, currency, retailer, url, date}]",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="ratings",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Ratings: [{source, score, max_score, reviewer, date, url}]",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="taste_profile",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Tasting notes: nose, palate, finish, flavor_tags, overall_notes",
            ),
        ),
        migrations.AlterField(
            model_name="articleproductmention",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="article_mentions_rel",
                to="crawler.discoveredproduct",
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["mention_count"], name="discovered__mention_5ec2c7_idx"
            ),
        ),
    ]
