# Generated by Django 5.2.8 on 2025-12-30 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0004_discoveredproduct_best_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="availability_score",
            field=models.IntegerField(
                blank=True,
                help_text="Availability score (1-10, 10=widely available, 1=extremely rare)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="avg_price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average price across retailers (USD)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="batch_size",
            field=models.IntegerField(
                blank=True, help_text="Number of bottles in batch/release", null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="buzz_score",
            field=models.IntegerField(
                blank=True,
                help_text="Social media + press mention intensity (1-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="in_stock_count",
            field=models.IntegerField(
                default=0, help_text="Number of retailers with product in stock"
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="is_allocated",
            field=models.BooleanField(
                default=False, help_text="Whether distribution is allocated/restricted"
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="is_limited_edition",
            field=models.BooleanField(
                default=False, help_text="Whether this is a limited edition release"
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="max_price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum price found (USD)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="min_price_usd",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum price found (USD)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="price_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("budget", "Budget"),
                    ("value", "Value"),
                    ("mid_range", "Mid-Range"),
                    ("premium", "Premium"),
                    ("ultra_premium", "Ultra-Premium"),
                    ("luxury", "Luxury"),
                ],
                help_text="Price tier: budget, value, mid_range, premium, ultra_premium, luxury",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="price_volatility",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price volatility metric (standard deviation)",
                max_digits=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="release_year",
            field=models.IntegerField(
                blank=True,
                help_text="Year of release (for limited editions)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="retailer_count",
            field=models.IntegerField(
                default=0, help_text="Number of retailers carrying this product"
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="search_interest",
            field=models.IntegerField(
                blank=True, help_text="Google Trends search interest score", null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="target_audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("beginner", "Beginner"),
                    ("casual", "Casual"),
                    ("enthusiast", "Enthusiast"),
                    ("collector", "Collector"),
                    ("investor", "Investor"),
                ],
                help_text="Target audience: beginner, casual, enthusiast, collector, investor",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="trend_direction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("rising", "Rising"),
                    ("stable", "Stable"),
                    ("declining", "Declining"),
                ],
                help_text="Trend direction: rising, stable, declining",
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="trend_score",
            field=models.IntegerField(
                blank=True,
                help_text="Calculated popularity score (1-100)",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["trend_score"], name="discovered__trend_s_0277aa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["price_tier"], name="discovered__price_t_5c5999_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(
                fields=["availability_score"], name="discovered__availab_0e2b45_idx"
            ),
        ),
    ]
