# Generated by Django 5.2.8 on 2025-12-30 14:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0005_add_demand_market_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAvailability",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "retailer",
                    models.CharField(help_text="Name of the retailer", max_length=200),
                ),
                (
                    "retailer_url",
                    models.URLField(
                        help_text="URL to the product page on the retailer's site"
                    ),
                ),
                (
                    "retailer_country",
                    models.CharField(
                        help_text="Country where the retailer is based", max_length=100
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        help_text="Whether the product is currently in stock"
                    ),
                ),
                (
                    "stock_level",
                    models.CharField(
                        choices=[
                            ("in_stock", "In Stock"),
                            ("low_stock", "Low Stock"),
                            ("out_of_stock", "Out of Stock"),
                            ("pre_order", "Pre-Order"),
                            ("discontinued", "Discontinued"),
                        ],
                        help_text="Stock level: in_stock, low_stock, out_of_stock, pre_order, discontinued",
                        max_length=20,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current price in the retailer's currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        help_text="ISO 4217 currency code (e.g., USD, EUR, GBP)",
                        max_length=3,
                    ),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price normalized to USD for comparison",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price normalized to EUR for comparison",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "last_checked",
                    models.DateTimeField(
                        help_text="When this availability was last checked"
                    ),
                ),
                (
                    "price_changed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the price changed since last check",
                    ),
                ),
                (
                    "previous_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Previous price before the last change",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this availability record is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Availability",
                "verbose_name_plural": "Product Availabilities",
                "db_table": "product_availability",
                "ordering": ["-last_checked"],
                "indexes": [
                    models.Index(
                        fields=["product", "retailer"],
                        name="product_ava_product_7fe9d9_idx",
                    ),
                    models.Index(
                        fields=["last_checked"], name="product_ava_last_ch_d9107c_idx"
                    ),
                    models.Index(
                        fields=["stock_level"], name="product_ava_stock_l_4bcd07_idx"
                    ),
                ],
            },
        ),
    ]
