# Generated by Django 5.2.8 on 2025-12-30 15:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0006_add_product_availability"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryInsight",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        help_text="Product type: whiskey, port_wine, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        help_text="Sub-category: bourbon, scotch_single_malt, tawny, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Geographic region (e.g., Islay, Kentucky)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country (e.g., Scotland, USA, Japan)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "total_products",
                    models.IntegerField(
                        help_text="Total number of products in this category"
                    ),
                ),
                (
                    "products_with_awards",
                    models.IntegerField(
                        help_text="Number of products with at least one award"
                    ),
                ),
                (
                    "avg_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average price in USD across category",
                        max_digits=10,
                    ),
                ),
                (
                    "median_price_usd",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Median price in USD across category",
                        max_digits=10,
                    ),
                ),
                (
                    "avg_price_eur",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average price in EUR across category",
                        max_digits=10,
                    ),
                ),
                (
                    "avg_rating",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average rating across rated products in category",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "trending_direction",
                    models.CharField(
                        choices=[
                            ("hot", "Hot"),
                            ("rising", "Rising"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                            ("cold", "Cold"),
                        ],
                        help_text="Market trend: hot, rising, stable, declining, cold",
                        max_length=10,
                    ),
                ),
                (
                    "market_growth",
                    models.CharField(
                        blank=True,
                        help_text="Year-over-year growth indicator (e.g., '+15% YoY')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "avg_price_change_30d",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average price change in the last 30 days",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this insight was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Insight",
                "verbose_name_plural": "Category Insights",
                "db_table": "category_insight",
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["product_type", "sub_category"],
                        name="category_in_product_108d88_idx",
                    ),
                    models.Index(
                        fields=["trending_direction"],
                        name="category_in_trendin_53a5be_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_type", "sub_category", "region", "country"),
                        name="unique_category_insight",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
