# Generated by Django 5.2.8 on 2025-12-30 15:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0007_add_category_insight"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recommendation_score",
                    models.IntegerField(
                        help_text="Overall recommendation score (1-100)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "recommendation_tier",
                    models.CharField(
                        choices=[
                            ("must_stock", "Must Stock"),
                            ("recommended", "Recommended"),
                            ("consider", "Consider"),
                            ("watch", "Watch"),
                            ("skip", "Skip"),
                        ],
                        help_text="Recommendation tier: must_stock, recommended, consider, watch, skip",
                        max_length=20,
                    ),
                ),
                (
                    "recommendation_reason",
                    models.TextField(
                        help_text="AI-generated explanation for the recommendation"
                    ),
                ),
                (
                    "demand_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Demand/popularity score (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "quality_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Quality/ratings score (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "value_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Value for money score (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "uniqueness_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Product uniqueness score (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "trend_score_factor",
                    models.IntegerField(
                        blank=True,
                        help_text="Trend/momentum score (1-10)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "category_gap_fill",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this product fills a gap in inventory category",
                    ),
                ),
                (
                    "complements_existing",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this product complements existing inventory",
                    ),
                ),
                (
                    "margin_potential",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("premium", "Premium"),
                        ],
                        help_text="Margin potential: low, medium, high, premium",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "turnover_estimate",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("slow", "Slow"),
                            ("moderate", "Moderate"),
                            ("fast", "Fast"),
                            ("very_fast", "Very Fast"),
                        ],
                        help_text="Turnover estimate: slow, moderate, fast, very_fast",
                        max_length=15,
                        null=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        help_text="Risk level: low, medium, high",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "suggested_quantity",
                    models.IntegerField(
                        blank=True,
                        help_text="Suggested quantity to purchase",
                        null=True,
                    ),
                ),
                (
                    "suggested_retail_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Suggested retail price",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "estimated_margin_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Estimated margin percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "reorder_threshold",
                    models.IntegerField(
                        blank=True,
                        help_text="Suggested reorder threshold quantity",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the recommendation was created",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the recommendation expires (null = never)",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the recommendation is currently active",
                    ),
                ),
                (
                    "acted_upon",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the recommendation was acted upon",
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("success", "Success"),
                            ("moderate", "Moderate"),
                            ("poor", "Poor"),
                        ],
                        help_text="Outcome after acting: success, moderate, poor",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this recommendation is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Recommendation",
                "verbose_name_plural": "Purchase Recommendations",
                "db_table": "purchase_recommendation",
                "ordering": ["-recommendation_score", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recommendation_score"],
                        name="purchase_re_recomme_2e284c_idx",
                    ),
                    models.Index(
                        fields=["recommendation_tier"],
                        name="purchase_re_recomme_ba1c4a_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="purchase_re_expires_cd7c53_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="purchase_re_is_acti_2e8940_idx"
                    ),
                ],
            },
        ),
    ]
