# Generated by Django 5.2.8 on 2025-12-30 15:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0008_purchase_recommendation"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        help_text="Name of the product in shop inventory",
                        max_length=255,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        help_text="Product type: whiskey, port_wine, etc.",
                        max_length=50,
                    ),
                ),
                (
                    "sub_category",
                    models.CharField(
                        help_text="Sub-category: bourbon, scotch_single_malt, tawny, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Geographic region (e.g., Islay, Kentucky)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "price_tier",
                    models.CharField(
                        choices=[
                            ("budget", "Budget"),
                            ("value", "Value"),
                            ("mid_range", "Mid-Range"),
                            ("premium", "Premium"),
                            ("ultra_premium", "Ultra-Premium"),
                            ("luxury", "Luxury"),
                        ],
                        help_text="Price tier: budget, value, mid_range, premium, ultra_premium, luxury",
                        max_length=20,
                    ),
                ),
                (
                    "current_stock",
                    models.IntegerField(help_text="Current quantity in stock"),
                ),
                (
                    "reorder_point",
                    models.IntegerField(help_text="Stock level at which to reorder"),
                ),
                (
                    "monthly_sales_avg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average monthly sales quantity",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "last_restocked",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the item was last restocked",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this inventory item is active (not discontinued)",
                    ),
                ),
                (
                    "matched_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matched DiscoveredProduct for comparison (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shop_inventory",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shop Inventory",
                "verbose_name_plural": "Shop Inventory Items",
                "db_table": "shop_inventory",
                "ordering": ["product_name"],
                "indexes": [
                    models.Index(
                        fields=["matched_product"],
                        name="shop_invent_matched_2261c1_idx",
                    ),
                    models.Index(
                        fields=["product_type", "sub_category"],
                        name="shop_invent_product_204ae8_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="shop_invent_is_acti_dfc214_idx"
                    ),
                ],
            },
        ),
    ]
