# Generated by Django 5.0.1 on 2024-12-30
# Task Group 25: European Market Fields Migration

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    """
    Task Group 25: Add European market fields to DiscoveredProduct.

    This migration adds fields to enable the system to be specifically
    tailored for German/European spirits retailers:
    - EUR pricing fields (primary_currency, price_eur, VAT handling)
    - Import/availability fields (origin_region, import_complexity, etc.)
    - EU regulatory fields (label compliance, allergens, organic, bottle size)
    - German market fit scoring
    - German language fields (name_de, description_de)
    """

    dependencies = [
        ('crawler', '0009_shop_inventory'),
    ]

    operations = [
        # EUR Pricing Fields
        migrations.AddField(
            model_name='discoveredproduct',
            name='primary_currency',
            field=models.CharField(
                default='EUR',
                help_text='Primary currency for this product (ISO 4217)',
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='price_eur',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Normalized price in EUR for comparison',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='price_includes_vat',
            field=models.BooleanField(
                default=True,
                help_text='Whether price includes VAT (EU retail prices typically include VAT)',
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='vat_rate',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='VAT rate percentage (e.g., 19.00 for Germany)',
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='price_excl_vat',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Price excluding VAT',
                max_digits=10,
                null=True,
            ),
        ),

        # Import/Availability Fields
        migrations.AddField(
            model_name='discoveredproduct',
            name='origin_region',
            field=models.CharField(
                blank=True,
                choices=[
                    ('eu', 'European Union'),
                    ('uk', 'United Kingdom'),
                    ('usa', 'United States'),
                    ('japan', 'Japan'),
                    ('rest_of_world', 'Rest of World'),
                ],
                help_text='Geographic origin region: eu, uk, usa, japan, rest_of_world',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='import_complexity',
            field=models.CharField(
                blank=True,
                choices=[
                    ('eu_domestic', 'EU Domestic'),
                    ('uk_post_brexit', 'UK Post-Brexit'),
                    ('usa_import', 'USA Import'),
                    ('japan_import', 'Japan Import'),
                    ('other_import', 'Other Import'),
                ],
                help_text='Import complexity: eu_domestic, uk_post_brexit, usa_import, japan_import, other_import',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='eu_available',
            field=models.BooleanField(
                default=False,
                help_text='Whether product is available in the EU market',
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='german_available',
            field=models.BooleanField(
                default=False,
                help_text='Whether product is available in the German market',
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='estimated_landed_cost_eur',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='Estimated landed cost in EUR including duties and shipping',
                max_digits=10,
                null=True,
            ),
        ),

        # EU Regulatory Fields
        migrations.AddField(
            model_name='discoveredproduct',
            name='eu_label_compliant',
            field=models.BooleanField(
                blank=True,
                help_text='Whether product has EU-compliant labeling',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='contains_allergens',
            field=models.BooleanField(
                blank=True,
                help_text='Whether product contains allergens requiring disclosure',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='organic_certified',
            field=models.BooleanField(
                blank=True,
                help_text='Whether product has organic certification',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='bottle_size_ml',
            field=models.IntegerField(
                blank=True,
                help_text='Bottle size in milliliters (700ml spirits, 750ml wine typical in EU)',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='alcohol_duty_category',
            field=models.CharField(
                blank=True,
                help_text='Alcohol duty category for tax purposes',
                max_length=100,
                null=True,
            ),
        ),

        # German Market Fit Field
        migrations.AddField(
            model_name='discoveredproduct',
            name='german_market_fit',
            field=models.IntegerField(
                blank=True,
                help_text='German market fit score (1-10, based on price, availability, preferences)',
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),

        # German Language Fields
        migrations.AddField(
            model_name='discoveredproduct',
            name='name_de',
            field=models.CharField(
                blank=True,
                help_text='German name if different from English name',
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name='discoveredproduct',
            name='description_de',
            field=models.TextField(
                blank=True,
                help_text='German description/tasting notes',
                null=True,
            ),
        ),

        # Add indexes for European market fields
        migrations.AddIndex(
            model_name='discoveredproduct',
            index=models.Index(
                fields=['origin_region'],
                name='discovered__origin__idx',
            ),
        ),
        migrations.AddIndex(
            model_name='discoveredproduct',
            index=models.Index(
                fields=['german_available'],
                name='discovered__german___idx',
            ),
        ),
        migrations.AddIndex(
            model_name='discoveredproduct',
            index=models.Index(
                fields=['german_market_fit'],
                name='discovered__german_m_idx',
            ),
        ),
    ]
