# Generated by Django 5.2.8 on 2025-12-30 16:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0010_add_european_market_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrawlerMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        help_text="Date for this metrics record (one per day)",
                        unique=True,
                    ),
                ),
                (
                    "pages_crawled",
                    models.IntegerField(
                        default=0, help_text="Total pages crawled on this date"
                    ),
                ),
                (
                    "pages_succeeded",
                    models.IntegerField(
                        default=0, help_text="Pages successfully crawled"
                    ),
                ),
                (
                    "pages_failed",
                    models.IntegerField(
                        default=0, help_text="Pages that failed to crawl"
                    ),
                ),
                (
                    "crawl_success_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Crawl success rate percentage (succeeded/crawled * 100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "products_extracted",
                    models.IntegerField(
                        default=0,
                        help_text="Total products extracted from crawled pages",
                    ),
                ),
                (
                    "products_created",
                    models.IntegerField(
                        default=0, help_text="New products created in database"
                    ),
                ),
                (
                    "products_merged",
                    models.IntegerField(
                        default=0, help_text="Products merged with existing records"
                    ),
                ),
                (
                    "products_flagged_review",
                    models.IntegerField(
                        default=0, help_text="Products flagged for manual review"
                    ),
                ),
                (
                    "extraction_success_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Extraction success rate percentage",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "avg_completeness_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average completeness score for extracted products (1-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "avg_confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average extraction confidence score (0.00-1.00)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "conflicts_detected",
                    models.IntegerField(
                        default=0, help_text="Number of data conflicts detected"
                    ),
                ),
                (
                    "duplicates_merged",
                    models.IntegerField(
                        default=0, help_text="Number of duplicate records merged"
                    ),
                ),
                (
                    "serpapi_queries",
                    models.IntegerField(
                        default=0, help_text="Number of SerpAPI queries made"
                    ),
                ),
                (
                    "scrapingbee_requests",
                    models.IntegerField(
                        default=0, help_text="Number of ScrapingBee requests made"
                    ),
                ),
                (
                    "ai_enhancement_calls",
                    models.IntegerField(
                        default=0, help_text="Number of AI enhancement API calls"
                    ),
                ),
                (
                    "wayback_saves",
                    models.IntegerField(
                        default=0,
                        help_text="Number of pages archived to Wayback Machine",
                    ),
                ),
                (
                    "avg_crawl_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Average crawl time per page in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "avg_extraction_time_ms",
                    models.IntegerField(
                        blank=True,
                        help_text="Average extraction time per page in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "queue_depth",
                    models.IntegerField(
                        default=0, help_text="Queue depth at end of day"
                    ),
                ),
            ],
            options={
                "verbose_name": "Crawler Metrics",
                "verbose_name_plural": "Crawler Metrics",
                "db_table": "crawler_metrics",
                "ordering": ["-date"],
            },
        ),
        migrations.RenameIndex(
            model_name="discoveredproduct",
            new_name="discovered__origin__384b41_idx",
            old_name="discovered__origin__idx",
        ),
        migrations.RenameIndex(
            model_name="discoveredproduct",
            new_name="discovered__german__772a6c_idx",
            old_name="discovered__german___idx",
        ),
        migrations.RenameIndex(
            model_name="discoveredproduct",
            new_name="discovered__german__23106d_idx",
            old_name="discovered__german_m_idx",
        ),
        migrations.AddIndex(
            model_name="crawlermetrics",
            index=models.Index(fields=["date"], name="crawler_met_date_99d3a9_idx"),
        ),
    ]
