# Generated by Django 5.2.8 on 2025-12-30 16:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0011_add_crawler_metrics_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoverySourceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique name for this discovery source",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "base_url",
                    models.URLField(help_text="Base URL of the discovery source"),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("award_competition", "Award/Competition"),
                            ("review_blog", "Review/Blog"),
                            ("retailer", "Retailer"),
                            ("distillery_official", "Distillery Official"),
                            ("news_outlet", "News Outlet"),
                            ("aggregator", "Aggregator"),
                        ],
                        help_text="Type of source: award_competition, review_blog, retailer, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "crawl_priority",
                    models.IntegerField(
                        help_text="Crawl priority (1-10, higher = more important)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "crawl_frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("on_demand", "On Demand"),
                        ],
                        help_text="How often to crawl: daily, weekly, monthly, on_demand",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this source is active for crawling",
                    ),
                ),
                (
                    "reliability_score",
                    models.IntegerField(
                        help_text="Reliability score for conflict resolution (1-10, higher = more reliable)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "requires_authentication",
                    models.BooleanField(
                        default=False,
                        help_text="Whether authentication is required to access this source",
                    ),
                ),
                (
                    "rate_limit_delay",
                    models.IntegerField(
                        default=1, help_text="Delay between requests in seconds"
                    ),
                ),
                (
                    "crawl_strategy",
                    models.CharField(
                        choices=[
                            ("simple", "Simple"),
                            ("js_render", "JS Render"),
                            ("stealth", "Stealth"),
                            ("manual", "Manual"),
                        ],
                        default="simple",
                        help_text="Crawl strategy: simple, js_render, stealth, manual",
                        max_length=20,
                    ),
                ),
                (
                    "detected_obstacles",
                    models.JSONField(
                        blank=True,
                        help_text="Detected obstacles during crawling (age gates, CAPTCHAs, etc.)",
                        null=True,
                    ),
                ),
                (
                    "strategy_confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the crawl strategy has been confirmed as working",
                    ),
                ),
                (
                    "custom_headers",
                    models.JSONField(
                        blank=True,
                        help_text="Custom HTTP headers for requests",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Notes about this source", null=True
                    ),
                ),
                (
                    "last_crawled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this source was last crawled",
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this source was created"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="When this source was last updated"
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Source Config",
                "verbose_name_plural": "Discovery Source Configs",
                "db_table": "discovery_source_config",
                "ordering": ["-crawl_priority", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="discovery_s_name_d0001f_idx"),
                    models.Index(
                        fields=["base_url"], name="discovery_s_base_ur_6cbbf1_idx"
                    ),
                    models.Index(
                        fields=["is_active", "crawl_priority"],
                        name="discovery_s_is_acti_a55545_idx",
                    ),
                    models.Index(
                        fields=["source_type"], name="discovery_s_source__52703a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CrawledSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        db_index=True,
                        help_text="URL of the crawled page (unique)",
                        max_length=2000,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the crawled page", max_length=500
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        help_text="SHA-256 hash of raw content for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("award_page", "Award Page"),
                            ("review_article", "Review Article"),
                            ("retailer_page", "Retailer Page"),
                            ("distillery_page", "Distillery Page"),
                            ("news_article", "News Article"),
                        ],
                        help_text="Type of crawled page: award_page, review_article, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="pending",
                        help_text="Processing status: pending, processed, failed, needs_review",
                        max_length=20,
                    ),
                ),
                (
                    "raw_content",
                    models.TextField(
                        blank=True, help_text="Raw HTML content of the page", null=True
                    ),
                ),
                (
                    "raw_content_cleared",
                    models.BooleanField(
                        default=False,
                        help_text="Whether raw content has been cleared after processing",
                    ),
                ),
                (
                    "wayback_url",
                    models.URLField(
                        blank=True,
                        help_text="Wayback Machine archive URL",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "wayback_saved_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the page was saved to Wayback Machine",
                        null=True,
                    ),
                ),
                (
                    "wayback_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("saved", "Saved"),
                            ("failed", "Failed"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="pending",
                        help_text="Wayback archival status: pending, saved, failed, not_applicable",
                        max_length=20,
                    ),
                ),
                (
                    "crawl_attempts",
                    models.IntegerField(
                        default=0, help_text="Number of crawl attempts for this URL"
                    ),
                ),
                (
                    "last_crawl_error",
                    models.TextField(
                        blank=True,
                        help_text="Error message from last failed crawl attempt",
                        null=True,
                    ),
                ),
                (
                    "crawl_strategy_used",
                    models.CharField(
                        blank=True,
                        help_text="Crawl strategy used for successful crawl",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "detected_obstacles",
                    models.JSONField(
                        blank=True,
                        help_text="Obstacles detected during crawling",
                        null=True,
                    ),
                ),
                (
                    "crawled_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When this page was crawled"
                    ),
                ),
                (
                    "discovery_source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Discovery source this page came from (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crawled_sources",
                        to="crawler.discoverysourceconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crawled Source",
                "verbose_name_plural": "Crawled Sources",
                "db_table": "crawled_source",
                "ordering": ["-crawled_at"],
                "indexes": [
                    models.Index(fields=["url"], name="crawled_sou_url_404abd_idx"),
                    models.Index(
                        fields=["content_hash"], name="crawled_sou_content_b3590b_idx"
                    ),
                    models.Index(
                        fields=["extraction_status", "crawled_at"],
                        name="crawled_sou_extract_bcc96f_idx",
                    ),
                    models.Index(
                        fields=["discovery_source", "crawled_at"],
                        name="crawled_sou_discove_6ada4a_idx",
                    ),
                    models.Index(
                        fields=["wayback_status"], name="crawled_sou_wayback_67a0f6_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceMetrics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(help_text="Date for this metrics record")),
                (
                    "pages_crawled",
                    models.IntegerField(
                        default=0,
                        help_text="Total pages crawled from this source on this date",
                    ),
                ),
                (
                    "pages_succeeded",
                    models.IntegerField(
                        default=0,
                        help_text="Pages successfully crawled from this source",
                    ),
                ),
                (
                    "products_found",
                    models.IntegerField(
                        default=0,
                        help_text="Products found from this source on this date",
                    ),
                ),
                (
                    "avg_products_per_page",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average products found per page",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "avg_confidence",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average extraction confidence score (0.00-1.00)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "errors",
                    models.JSONField(
                        default=list,
                        help_text="Error types and counts: [{'type': 'connection_timeout', 'count': 5}, ...]",
                    ),
                ),
                (
                    "discovery_source",
                    models.ForeignKey(
                        help_text="Discovery source this metrics record is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="crawler.discoverysourceconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Metrics",
                "verbose_name_plural": "Source Metrics",
                "db_table": "source_metrics",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="source_metr_date_abd077_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "discovery_source"),
                        name="unique_source_metrics_date_source",
                    )
                ],
            },
        ),
    ]
