# Generated by Django 5.2.8 on 2025-12-30 17:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0012_add_source_metrics_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this alert rule", max_length=200
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        help_text="Name of the metric to monitor (e.g., 'crawl_success_rate', 'queue_depth')",
                        max_length=100,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("below", "Below"),
                            ("above", "Above"),
                            ("equals", "Equals"),
                            ("changed_by", "Changed By"),
                        ],
                        help_text="Condition: below, above, equals, changed_by",
                        max_length=20,
                    ),
                ),
                (
                    "threshold",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Threshold value for the condition",
                        max_digits=12,
                    ),
                ),
                (
                    "window_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Time window in hours for metric evaluation",
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        help_text="Severity level: info, warning, critical",
                        max_length=10,
                    ),
                ),
                (
                    "notification_channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("slack", "Slack"),
                            ("sentry", "Sentry"),
                        ],
                        default="sentry",
                        help_text="Notification channel: email, slack, sentry",
                        max_length=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this alert rule is active"
                    ),
                ),
                (
                    "cooldown_hours",
                    models.IntegerField(
                        default=4,
                        help_text="Minimum hours between repeated alerts for this rule",
                    ),
                ),
                (
                    "last_triggered",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this alert was last triggered",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Alert Rule",
                "verbose_name_plural": "Alert Rules",
                "db_table": "alert_rule",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="alert_rule_is_acti_f06957_idx"
                    ),
                    models.Index(
                        fields=["metric"], name="alert_rule_metric_f0308b_idx"
                    ),
                ],
            },
        ),
    ]
