# Generated by Django 5.2.8 on 2025-12-30 18:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0013_add_alert_rule_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="award_count",
            field=models.IntegerField(
                default=0, help_text="Total number of awards for this product"
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="price_count",
            field=models.IntegerField(
                default=0, help_text="Total number of price observations"
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="rating_count",
            field=models.IntegerField(default=0, help_text="Total number of ratings"),
        ),
        migrations.CreateModel(
            name="DiscoveredBrand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Brand name", max_length=200)),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="URL-safe identifier",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True,
                        help_text="Country of origin",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="Region within country",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "headquarters_country",
                    models.CharField(
                        blank=True,
                        help_text="Country where headquarters is located",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "official_website",
                    models.URLField(
                        blank=True, help_text="Official brand website", null=True
                    ),
                ),
                (
                    "founded_year",
                    models.IntegerField(
                        blank=True, help_text="Year the brand was founded", null=True
                    ),
                ),
                (
                    "product_count",
                    models.IntegerField(
                        default=0, help_text="Number of products from this brand"
                    ),
                ),
                (
                    "award_count",
                    models.IntegerField(
                        default=0, help_text="Total awards won by the brand"
                    ),
                ),
                (
                    "mention_count",
                    models.IntegerField(
                        default=0, help_text="Number of source mentions"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discovered Brand",
                "verbose_name_plural": "Discovered Brands",
                "db_table": "discovered_brand",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="discovered__name_a7fa94_idx"),
                    models.Index(
                        fields=["country"], name="discovered__country_54ef6d_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                help_text="Brand this product belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="crawler.discoveredbrand",
            ),
        ),
        migrations.CreateModel(
            name="PortWineDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("ruby", "Ruby"),
                            ("tawny", "Tawny"),
                            ("white", "White"),
                            ("rose", "Rose"),
                            ("lbv", "Late Bottled Vintage (LBV)"),
                            ("vintage", "Vintage"),
                            ("colheita", "Colheita"),
                            ("crusted", "Crusted"),
                            ("single_quinta", "Single Quinta"),
                            ("garrafeira", "Garrafeira"),
                        ],
                        help_text="Port wine style",
                        max_length=20,
                    ),
                ),
                (
                    "indication_age",
                    models.CharField(
                        blank=True,
                        help_text="Age indication (e.g., '20 Year', '10 Year')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "harvest_year",
                    models.IntegerField(
                        blank=True, help_text="Year of harvest/vintage", null=True
                    ),
                ),
                (
                    "bottling_year",
                    models.IntegerField(
                        blank=True, help_text="Year of bottling", null=True
                    ),
                ),
                (
                    "grape_varieties",
                    models.JSONField(
                        blank=True, default=list, help_text="Grape varieties used"
                    ),
                ),
                (
                    "quinta",
                    models.CharField(
                        blank=True,
                        help_text="Quinta (estate) name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "douro_subregion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("baixo_corgo", "Baixo Corgo"),
                            ("cima_corgo", "Cima Corgo"),
                            ("douro_superior", "Douro Superior"),
                        ],
                        help_text="Douro subregion",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "producer_house",
                    models.CharField(
                        help_text="Port house/producer name", max_length=200
                    ),
                ),
                (
                    "aging_vessel",
                    models.CharField(
                        blank=True,
                        help_text="Type of vessel used for aging",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "decanting_required",
                    models.BooleanField(
                        default=False, help_text="Whether decanting is recommended"
                    ),
                ),
                (
                    "drinking_window",
                    models.CharField(
                        blank=True,
                        help_text="Optimal drinking window (e.g., '2025-2060')",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="The product these details belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="port_details",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Port Wine Details",
                "verbose_name_plural": "Port Wine Details",
                "db_table": "port_wine_details",
            },
        ),
        migrations.CreateModel(
            name="WhiskeyDetails",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "whiskey_type",
                    models.CharField(
                        choices=[
                            ("scotch_single_malt", "Scotch Single Malt"),
                            ("scotch_blend", "Scotch Blend"),
                            ("bourbon", "Bourbon"),
                            ("tennessee", "Tennessee"),
                            ("rye", "Rye"),
                            ("irish_single_pot", "Irish Single Pot Still"),
                            ("irish_single_malt", "Irish Single Malt"),
                            ("irish_blend", "Irish Blend"),
                            ("japanese", "Japanese"),
                            ("canadian", "Canadian"),
                            ("indian", "Indian"),
                            ("taiwanese", "Taiwanese"),
                            ("australian", "Australian"),
                            ("american_single_malt", "American Single Malt"),
                            ("world_whiskey", "World Whiskey"),
                        ],
                        help_text="Type of whiskey",
                        max_length=30,
                    ),
                ),
                (
                    "whiskey_country",
                    models.CharField(help_text="Country of origin", max_length=100),
                ),
                (
                    "whiskey_region",
                    models.CharField(
                        blank=True,
                        help_text="Region within country (e.g., Speyside, Kentucky)",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "distillery",
                    models.CharField(
                        blank=True,
                        help_text="Distillery name",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "mash_bill",
                    models.CharField(
                        blank=True,
                        help_text="Grain composition",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "cask_type",
                    models.CharField(
                        blank=True,
                        help_text="Primary cask type used",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "cask_finish",
                    models.CharField(
                        blank=True,
                        help_text="Finishing cask if any",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "cask_strength",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this is a cask strength release",
                    ),
                ),
                (
                    "single_cask",
                    models.BooleanField(
                        default=False, help_text="Whether this is from a single cask"
                    ),
                ),
                (
                    "cask_number",
                    models.CharField(
                        blank=True,
                        help_text="Cask number for single cask releases",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "vintage_year",
                    models.IntegerField(
                        blank=True, help_text="Year of distillation", null=True
                    ),
                ),
                (
                    "bottling_year",
                    models.IntegerField(
                        blank=True, help_text="Year of bottling", null=True
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, help_text="Batch number", max_length=50, null=True
                    ),
                ),
                (
                    "peated",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether this whiskey is peated",
                        null=True,
                    ),
                ),
                (
                    "peat_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unpeated", "Unpeated"),
                            ("lightly_peated", "Lightly Peated"),
                            ("medium_peated", "Medium Peated"),
                            ("heavily_peated", "Heavily Peated"),
                        ],
                        help_text="Level of peat",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "chill_filtered",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether chill filtration was used",
                        null=True,
                    ),
                ),
                (
                    "color_added",
                    models.BooleanField(
                        blank=True,
                        help_text="Whether color (E150a) was added",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        help_text="The product these details belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="whiskey_details",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Whiskey Details",
                "verbose_name_plural": "Whiskey Details",
                "db_table": "whiskey_details",
            },
        ),
        migrations.CreateModel(
            name="CrawlSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(help_text="When the next crawl should run"),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, help_text="When the last crawl ran", null=True
                    ),
                ),
                (
                    "last_status",
                    models.CharField(
                        blank=True, help_text="Status of the last crawl", max_length=20
                    ),
                ),
                (
                    "consecutive_errors",
                    models.IntegerField(
                        default=0, help_text="Number of consecutive errors"
                    ),
                ),
                (
                    "current_backoff_hours",
                    models.IntegerField(
                        default=0, help_text="Current backoff in hours"
                    ),
                ),
                (
                    "priority_boost",
                    models.IntegerField(
                        default=0, help_text="Priority boost for this schedule"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this schedule is active"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Discovery source this schedule is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="crawler.discoverysourceconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Crawl Schedule",
                "verbose_name_plural": "Crawl Schedules",
                "db_table": "crawl_schedule",
                "ordering": ["next_run"],
                "indexes": [
                    models.Index(
                        fields=["next_run", "is_active"],
                        name="crawl_sched_next_ru_d7b174_idx",
                    ),
                    models.Index(
                        fields=["source"], name="crawl_sched_source__d58d00_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence score for extraction (0.0-1.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "mention_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of mention",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mention_count",
                    models.IntegerField(
                        default=1, help_text="Number of times mentioned in this source"
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source that mentioned this brand",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brands",
                        to="crawler.crawledsource",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="The brand",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sources",
                        to="crawler.discoveredbrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Source",
                "verbose_name_plural": "Brand Sources",
                "db_table": "brand_source",
                "indexes": [
                    models.Index(
                        fields=["brand"], name="brand_sourc_brand_i_a2383c_idx"
                    ),
                    models.Index(
                        fields=["source"], name="brand_sourc_source__32b417_idx"
                    ),
                ],
                "unique_together": {("brand", "source")},
            },
        ),
        migrations.CreateModel(
            name="BrandAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "competition",
                    models.CharField(
                        help_text="Competition/award name", max_length=200
                    ),
                ),
                (
                    "competition_country",
                    models.CharField(
                        help_text="Country where competition is held", max_length=100
                    ),
                ),
                ("year", models.IntegerField(help_text="Year the award was given")),
                (
                    "medal",
                    models.CharField(
                        choices=[
                            ("double_gold", "Double Gold"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("best_in_class", "Best in Class"),
                            ("category_winner", "Category Winner"),
                        ],
                        help_text="Medal/award level",
                        max_length=20,
                    ),
                ),
                (
                    "award_category",
                    models.CharField(
                        help_text="Category within the competition", max_length=200
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="Score given (if applicable)", null=True
                    ),
                ),
                (
                    "award_url",
                    models.URLField(
                        blank=True, help_text="URL to award page", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "brand",
                    models.ForeignKey(
                        help_text="The brand that won this award",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards",
                        to="crawler.discoveredbrand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Award",
                "verbose_name_plural": "Brand Awards",
                "db_table": "brand_award",
                "ordering": ["-year", "competition"],
                "indexes": [
                    models.Index(
                        fields=["brand", "year"], name="brand_award_brand_i_e2f370_idx"
                    ),
                    models.Index(
                        fields=["competition"], name="brand_award_competi_94d482_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="NewRelease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Product name", max_length=500)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("whiskey", "Whiskey"),
                            ("port_wine", "Port Wine"),
                            ("gin", "Gin"),
                            ("rum", "Rum"),
                            ("tequila", "Tequila"),
                            ("vodka", "Vodka"),
                            ("brandy", "Brandy"),
                            ("sake", "Sake"),
                        ],
                        help_text="Type of product",
                        max_length=20,
                    ),
                ),
                (
                    "release_status",
                    models.CharField(
                        choices=[
                            ("rumored", "Rumored"),
                            ("announced", "Announced"),
                            ("pre_order", "Pre-Order"),
                            ("released", "Released"),
                            ("cancelled", "Cancelled"),
                        ],
                        help_text="Current release status",
                        max_length=20,
                    ),
                ),
                (
                    "announced_date",
                    models.DateField(
                        blank=True,
                        help_text="When the release was announced",
                        null=True,
                    ),
                ),
                (
                    "expected_release_date",
                    models.DateField(
                        blank=True, help_text="Expected release date", null=True
                    ),
                ),
                (
                    "actual_release_date",
                    models.DateField(
                        blank=True, help_text="Actual release date", null=True
                    ),
                ),
                (
                    "expected_price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Expected price in EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "limited_edition",
                    models.BooleanField(
                        default=False, help_text="Whether this is a limited edition"
                    ),
                ),
                (
                    "expected_bottle_count",
                    models.IntegerField(
                        blank=True, help_text="Expected number of bottles", null=True
                    ),
                ),
                (
                    "hype_score",
                    models.IntegerField(
                        blank=True,
                        help_text="Calculated hype/interest score (1-100)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "source_urls",
                    models.JSONField(
                        default=list, help_text="URLs where this release was mentioned"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about the release",
                        null=True,
                    ),
                ),
                (
                    "is_tracked",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to continue tracking this release",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        help_text="Brand if known",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_releases",
                        to="crawler.discoveredbrand",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked product if it exists",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_releases",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "New Release",
                "verbose_name_plural": "New Releases",
                "db_table": "new_release",
                "ordering": ["-expected_release_date"],
                "indexes": [
                    models.Index(
                        fields=["release_status"], name="new_release_release_110618_idx"
                    ),
                    models.Index(
                        fields=["product_type"], name="new_release_product_7174e5_idx"
                    ),
                    models.Index(
                        fields=["expected_release_date"],
                        name="new_release_expecte_921e70_idx",
                    ),
                    models.Index(
                        fields=["is_tracked"], name="new_release_is_trac_807694_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("price_drop", "Price Drop"),
                            ("price_spike", "Price Spike"),
                            ("new_low", "New Low"),
                            ("back_in_stock", "Back in Stock"),
                        ],
                        help_text="Type of alert",
                        max_length=20,
                    ),
                ),
                (
                    "threshold_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Threshold that triggered the alert",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "triggered_value",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Actual value that triggered the alert",
                        max_digits=10,
                    ),
                ),
                (
                    "retailer",
                    models.CharField(
                        blank=True,
                        help_text="Retailer where price change was detected",
                        max_length=200,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this alert has been acknowledged",
                    ),
                ),
                (
                    "acknowledged_by",
                    models.CharField(
                        blank=True,
                        help_text="Who acknowledged this alert",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this alert was acknowledged",
                        null=True,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_alerts",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price Alert",
                "verbose_name_plural": "Price Alerts",
                "db_table": "price_alert",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="price_alert_product_00795c_idx"
                    ),
                    models.Index(
                        fields=["alert_type"], name="price_alert_alert_t_8e352c_idx"
                    ),
                    models.Index(
                        fields=["acknowledged"], name="price_alert_acknowl_d6b273_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "retailer",
                    models.CharField(help_text="Retailer name", max_length=200),
                ),
                (
                    "retailer_country",
                    models.CharField(help_text="Retailer's country", max_length=100),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in original currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(help_text="ISO 4217 currency code", max_length=3),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price normalized to EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "observed_at",
                    models.DateTimeField(help_text="When this price was observed"),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL where price was observed", null=True
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history_records",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Price History",
                "verbose_name_plural": "Price History Records",
                "db_table": "price_history",
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "retailer"],
                        name="price_histo_product_88d036_idx",
                    ),
                    models.Index(
                        fields=["observed_at"], name="price_histo_observe_1cc30f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductAward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "competition",
                    models.CharField(
                        help_text="Competition/award name", max_length=200
                    ),
                ),
                (
                    "competition_country",
                    models.CharField(
                        help_text="Country where competition is held", max_length=100
                    ),
                ),
                ("year", models.IntegerField(help_text="Year the award was given")),
                (
                    "medal",
                    models.CharField(
                        choices=[
                            ("double_gold", "Double Gold"),
                            ("gold", "Gold"),
                            ("silver", "Silver"),
                            ("bronze", "Bronze"),
                            ("best_in_class", "Best in Class"),
                            ("category_winner", "Category Winner"),
                        ],
                        help_text="Medal/award level",
                        max_length=20,
                    ),
                ),
                (
                    "award_category",
                    models.CharField(
                        help_text="Category within the competition", max_length=200
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, help_text="Score given (if applicable)", null=True
                    ),
                ),
                (
                    "award_url",
                    models.URLField(
                        blank=True, help_text="URL to award page", null=True
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to medal/certificate image",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product that won this award",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="awards_rel",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Award",
                "verbose_name_plural": "Product Awards",
                "db_table": "product_award",
                "ordering": ["-year", "competition"],
                "indexes": [
                    models.Index(
                        fields=["product", "year"],
                        name="product_awa_product_0f6b5d_idx",
                    ),
                    models.Index(
                        fields=["competition"], name="product_awa_competi_64bc9c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "raw_name",
                    models.CharField(
                        help_text="Original extracted product name", max_length=500
                    ),
                ),
                (
                    "normalized_name",
                    models.CharField(
                        help_text="Normalized product name for matching", max_length=500
                    ),
                ),
                (
                    "extracted_data",
                    models.JSONField(
                        default=dict, help_text="All extracted data for this product"
                    ),
                ),
                (
                    "match_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("matched", "Matched"),
                            ("new_product", "New Product"),
                            ("needs_review", "Needs Review"),
                        ],
                        default="pending",
                        help_text="Current matching status",
                        max_length=20,
                    ),
                ),
                (
                    "match_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Confidence of the match (0.0-1.0)",
                        max_digits=3,
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        blank=True,
                        help_text="Method used for matching (gtin, fingerprint, fuzzy, ai)",
                        max_length=20,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Matched existing product (if any)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matched_candidates",
                        to="crawler.discoveredproduct",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="Source this candidate was extracted from",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_candidates",
                        to="crawler.crawledsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Candidate",
                "verbose_name_plural": "Product Candidates",
                "db_table": "product_candidate",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["match_status"], name="product_can_match_s_8756d6_idx"
                    ),
                    models.Index(
                        fields=["normalized_name"],
                        name="product_can_normali_8e7c47_idx",
                    ),
                    models.Index(
                        fields=["source"], name="product_can_source__ca79f5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductFieldSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(help_text="Name of the field", max_length=100),
                ),
                (
                    "extracted_value",
                    models.TextField(
                        help_text="The extracted value (stored as string)"
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence score for this extraction (0.0-1.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_sources",
                        to="crawler.discoveredproduct",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source that provided this field value",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_extractions",
                        to="crawler.crawledsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Field Source",
                "verbose_name_plural": "Product Field Sources",
                "db_table": "product_field_source",
                "indexes": [
                    models.Index(
                        fields=["product", "field_name"],
                        name="product_fie_product_23ebad_idx",
                    ),
                    models.Index(
                        fields=["source"], name="product_fie_source__cc4e08_idx"
                    ),
                ],
                "unique_together": {("product", "field_name", "source")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(help_text="URL to the image")),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("bottle", "Bottle"),
                            ("label", "Label"),
                            ("packaging", "Packaging"),
                            ("lifestyle", "Lifestyle"),
                        ],
                        help_text="Type of image",
                        max_length=20,
                    ),
                ),
                (
                    "source",
                    models.CharField(help_text="Source of the image", max_length=200),
                ),
                (
                    "width",
                    models.IntegerField(
                        blank=True, help_text="Image width in pixels", null=True
                    ),
                ),
                (
                    "height",
                    models.IntegerField(
                        blank=True, help_text="Image height in pixels", null=True
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Whether this is the primary image"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this image belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images_rel",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
                "db_table": "product_image",
                "ordering": ["-is_primary"],
                "indexes": [
                    models.Index(
                        fields=["product"], name="product_ima_product_11eb72_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductPrice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "retailer",
                    models.CharField(help_text="Retailer name", max_length=200),
                ),
                (
                    "retailer_country",
                    models.CharField(help_text="Retailer's country", max_length=100),
                ),
                ("url", models.URLField(help_text="URL to product page at retailer")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price in original currency",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(help_text="ISO 4217 currency code", max_length=3),
                ),
                (
                    "price_usd",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price normalized to USD",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "price_eur",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Price normalized to EUR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "in_stock",
                    models.BooleanField(
                        blank=True, help_text="Whether product is in stock", null=True
                    ),
                ),
                (
                    "date_observed",
                    models.DateField(help_text="Date the price was observed"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this price is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Price",
                "verbose_name_plural": "Product Prices",
                "db_table": "product_price",
                "ordering": ["-date_observed"],
                "indexes": [
                    models.Index(
                        fields=["product", "retailer"],
                        name="product_pri_product_c5204b_idx",
                    ),
                    models.Index(
                        fields=["date_observed"], name="product_pri_date_ob_4f0d7d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductRating",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Rating source/platform name", max_length=200
                    ),
                ),
                (
                    "source_country",
                    models.CharField(
                        blank=True,
                        help_text="Country of the rating source",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, help_text="Rating score", max_digits=5
                    ),
                ),
                (
                    "max_score",
                    models.IntegerField(
                        help_text="Maximum possible score (e.g., 100, 5)"
                    ),
                ),
                (
                    "reviewer",
                    models.CharField(
                        blank=True, help_text="Reviewer name", max_length=200, null=True
                    ),
                ),
                (
                    "review_url",
                    models.URLField(
                        blank=True, help_text="URL to full review", null=True
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date of the rating", null=True
                    ),
                ),
                (
                    "review_count",
                    models.IntegerField(
                        blank=True,
                        help_text="Number of reviews (for aggregate scores)",
                        null=True,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product this rating is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings_rel",
                        to="crawler.discoveredproduct",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Rating",
                "verbose_name_plural": "Product Ratings",
                "db_table": "product_rating",
                "ordering": ["-score"],
                "indexes": [
                    models.Index(
                        fields=["product", "source"],
                        name="product_rat_product_134f14_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "extraction_confidence",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Confidence score for extraction (0.0-1.0)",
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "fields_extracted",
                    models.JSONField(
                        default=list,
                        help_text="List of field names extracted from this source",
                    ),
                ),
                (
                    "mention_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of mention",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "mention_count",
                    models.IntegerField(
                        default=1, help_text="Number of times mentioned in this source"
                    ),
                ),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_sources",
                        to="crawler.discoveredproduct",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        help_text="The source that mentioned this product",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="crawler.crawledsource",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Source",
                "verbose_name_plural": "Product Sources",
                "db_table": "product_source",
                "indexes": [
                    models.Index(
                        fields=["product"], name="product_sou_product_66765d_idx"
                    ),
                    models.Index(
                        fields=["source"], name="product_sou_source__d763fb_idx"
                    ),
                ],
                "unique_together": {("product", "source")},
            },
        ),
    ]
