# Generated by Django 5.2.8 on 2025-12-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0014_add_missing_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="abv",
            field=models.FloatField(
                blank=True, help_text="Alcohol by volume percentage", null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="age_statement",
            field=models.IntegerField(
                blank=True, help_text="Age statement in years", null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="name",
            field=models.CharField(
                blank=True, help_text="Product name (denormalized)", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="volume_ml",
            field=models.IntegerField(
                blank=True, help_text="Bottle volume in milliliters", null=True
            ),
        ),
    ]
