# Generated by Django 5.2.8 on 2025-12-30 18:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0015_add_product_denormalized_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="country",
            field=models.CharField(
                blank=True, help_text="Country of origin", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="region",
            field=models.CharField(
                blank=True,
                help_text="Product region (e.g., Speyside, Kentucky)",
                max_length=200,
                null=True,
            ),
        ),
    ]
