# Generated by Django 5.2.8 on 2025-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0016_add_product_region_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productsource",
            name="fields_extracted",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of field names extracted from this source",
            ),
        ),
    ]
