# Generated by Django 5.2.8 on 2025-12-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0017_add_blank_to_fields_extracted"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="gtin",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Global Trade Item Number (barcode) for exact product matching",
                max_length=14,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="discoveredproduct",
            index=models.Index(fields=["gtin"], name="discovered__gtin_90dfb0_idx"),
        ),
    ]
