# Generated by Django 5.2.8 on 2025-12-30

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add missing DiscoveredProduct fields for:
    - Completeness scoring (Task Group 19)
    - Tasting profile fields (Product Wizard field reference)
    - Conflict detection fields
    - Cask/maturation fields
    """

    dependencies = [
        ("crawler", "0018_add_gtin_field"),
    ]

    operations = [
        # ============================================================
        # Completeness Scoring Fields (Task Group 19)
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="completeness_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Completeness score 1-100 based on filled fields",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="completeness_tier",
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                choices=[
                    ("complete", "Complete"),
                    ("good", "Good"),
                    ("partial", "Partial"),
                    ("skeleton", "Skeleton"),
                ],
                help_text="Completeness tier: complete, good, partial, skeleton",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="missing_fields",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of missing field names for enrichment prioritization",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="enrichment_priority",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Enrichment priority score 1-10 (10=highest priority)",
            ),
        ),
        # ============================================================
        # Category Field
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="category",
            field=models.CharField(
                max_length=200,
                blank=True,
                null=True,
                help_text="Sub-category like 'Single Malt', 'Bourbon', 'Blended'",
            ),
        ),
        # ============================================================
        # Cask/Maturation Fields
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="primary_cask",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of primary cask types (e.g., ['ex-bourbon', 'american_oak'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="finishing_cask",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of finishing cask types (e.g., ['sherry', 'oloroso'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="wood_type",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of wood types (e.g., ['american_oak', 'european_oak'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="cask_treatment",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of cask treatments (e.g., ['charred', 'toasted'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="maturation_notes",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Detailed maturation/aging notes",
            ),
        ),
        # ============================================================
        # Conflict Detection Fields
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="has_conflicts",
            field=models.BooleanField(
                default=False,
                help_text="Whether this product has conflicting data from multiple sources",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="conflict_details",
            field=models.JSONField(
                blank=True,
                null=True,
                help_text="Details of conflicting data: {'field': 'abv', 'values': [...]}",
            ),
        ),
        # ============================================================
        # Appearance/Visual Fields
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="color_description",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Description of color (e.g., 'Deep amber with golden highlights')",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="color_intensity",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Color intensity rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="clarity",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="Clarity description (e.g., 'brilliant', 'hazy')",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="viscosity",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="Viscosity description (e.g., 'light', 'medium', 'oily')",
            ),
        ),
        # ============================================================
        # Nose/Aroma Fields
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="nose_description",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Overall nose/aroma description",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="primary_aromas",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of primary aroma notes (e.g., ['vanilla', 'honey', 'oak'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="primary_intensity",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Primary aroma intensity rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="secondary_aromas",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of secondary aroma notes (e.g., ['citrus', 'floral'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="aroma_evolution",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="How aromas evolve over time in the glass",
            ),
        ),
        # ============================================================
        # Palate Fields
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="palate_flavors",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of palate flavor notes (e.g., ['vanilla', 'toffee', 'cinnamon'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="initial_taste",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Initial taste/first impression on palate",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="mid_palate_evolution",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="How flavors develop mid-palate",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="flavor_intensity",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Flavor intensity rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="complexity",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Flavor complexity rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="mouthfeel",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="Mouthfeel description (e.g., 'oily', 'creamy', 'thin')",
            ),
        ),
        # ============================================================
        # Finish Fields
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="finish_length",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Finish length rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="warmth",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Warmth/heat rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="dryness",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Dryness rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="finish_flavors",
            field=models.JSONField(
                default=list,
                blank=True,
                help_text="List of finish flavor notes (e.g., ['oak', 'spice', 'tobacco'])",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="finish_evolution",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="How finish evolves and fades",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="final_notes",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Final lingering notes after finish",
            ),
        ),
        # ============================================================
        # Overall Assessment Fields
        # ============================================================
        migrations.AddField(
            model_name="discoveredproduct",
            name="balance",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Overall balance rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="overall_complexity",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Overall complexity rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="uniqueness",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Uniqueness/distinctiveness rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="drinkability",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Drinkability/accessibility rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="price_quality_ratio",
            field=models.IntegerField(
                blank=True,
                null=True,
                help_text="Price-quality ratio rating 1-10",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="experience_level",
            field=models.CharField(
                max_length=50,
                blank=True,
                null=True,
                help_text="Recommended experience level (e.g., 'beginner', 'enthusiast', 'expert')",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="serving_recommendation",
            field=models.CharField(
                max_length=200,
                blank=True,
                null=True,
                help_text="Serving recommendation (e.g., 'neat', 'on the rocks', 'cocktail')",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="food_pairings",
            field=models.TextField(
                blank=True,
                null=True,
                help_text="Recommended food pairings",
            ),
        ),
    ]
