# Generated by Django 5.2.8 on 2025-12-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0019_add_product_tasting_profile_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="bottler",
            field=models.CharField(
                blank=True,
                help_text="Independent bottler name (e.g., Gordon & MacPhail)",
                max_length=200,
                null=True,
            ),
        ),
    ]
