# Generated by Django 5.2.8 on 2026-01-01 12:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0020_add_bottler_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscoverySchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for this schedule.", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of this schedule's purpose.",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        help_text="How often to run this schedule.",
                        max_length=20,
                    ),
                ),
                (
                    "run_at_hour",
                    models.IntegerField(
                        default=3,
                        help_text="Hour (0-23) to run daily/weekly/monthly jobs. Ignored for hourly.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                (
                    "run_on_day",
                    models.IntegerField(
                        blank=True,
                        help_text="Day to run. For weekly: 0=Monday. For monthly: 1-31.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                (
                    "max_search_terms",
                    models.IntegerField(
                        default=20,
                        help_text="Maximum number of search terms to process per run.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "max_results_per_term",
                    models.IntegerField(
                        default=10,
                        help_text="Maximum number of search results to crawl per term.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(50),
                        ],
                    ),
                ),
                (
                    "search_categories",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of search term categories to include. Empty = all categories.",
                    ),
                ),
                (
                    "product_types",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of product types to include. Empty = all types.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Only active schedules will run."
                    ),
                ),
                (
                    "last_run",
                    models.DateTimeField(
                        blank=True, help_text="When this schedule last ran.", null=True
                    ),
                ),
                (
                    "next_run",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this schedule will next run.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discovery Schedule",
                "verbose_name_plural": "Discovery Schedules",
                "db_table": "discovery_schedule",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "next_run"],
                        name="discovery_s_is_acti_5e3260_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "search_terms_total",
                    models.IntegerField(
                        default=0, help_text="Total search terms to process."
                    ),
                ),
                (
                    "search_terms_processed",
                    models.IntegerField(
                        default=0, help_text="Search terms processed so far."
                    ),
                ),
                (
                    "urls_found",
                    models.IntegerField(
                        default=0, help_text="Total URLs found in search results."
                    ),
                ),
                (
                    "urls_crawled",
                    models.IntegerField(
                        default=0, help_text="URLs successfully crawled."
                    ),
                ),
                (
                    "urls_skipped",
                    models.IntegerField(
                        default=0,
                        help_text="URLs skipped (duplicates, blocked domains, etc.).",
                    ),
                ),
                (
                    "products_found",
                    models.IntegerField(
                        default=0, help_text="Total products identified."
                    ),
                ),
                (
                    "products_new",
                    models.IntegerField(
                        default=0, help_text="New products added to database."
                    ),
                ),
                (
                    "products_updated",
                    models.IntegerField(
                        default=0, help_text="Existing products updated."
                    ),
                ),
                (
                    "products_duplicates",
                    models.IntegerField(
                        default=0, help_text="Products skipped as duplicates."
                    ),
                ),
                (
                    "products_failed",
                    models.IntegerField(
                        default=0, help_text="Products that failed extraction."
                    ),
                ),
                (
                    "products_needs_review",
                    models.IntegerField(
                        default=0, help_text="Products flagged for human review."
                    ),
                ),
                (
                    "serpapi_calls_used",
                    models.IntegerField(
                        default=0, help_text="Number of SerpAPI calls made."
                    ),
                ),
                (
                    "scrapingbee_calls_used",
                    models.IntegerField(
                        default=0, help_text="Number of ScrapingBee calls made."
                    ),
                ),
                (
                    "ai_calls_used",
                    models.IntegerField(
                        default=0, help_text="Number of AI Enhancement calls made."
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        default=0, help_text="Number of errors encountered."
                    ),
                ),
                (
                    "error_log",
                    models.TextField(blank=True, help_text="Detailed error log."),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        blank=True,
                        help_text="The schedule that triggered this job, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="crawler.discoveryschedule",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Job",
                "verbose_name_plural": "Discovery Jobs",
                "db_table": "discovery_job",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchTerm",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "term_template",
                    models.CharField(
                        help_text="Search term template. Use {year} for current year substitution.",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("best_lists", "Best Lists"),
                            ("awards", "Awards & Recognition"),
                            ("new_releases", "New Releases"),
                            ("style", "Style & Flavor"),
                            ("value", "Value & Price"),
                            ("regional", "Regional/Type"),
                            ("seasonal", "Seasonal"),
                        ],
                        help_text="Category of the search term for organization and filtering.",
                        max_length=50,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("whiskey", "Whiskey"),
                            ("port_wine", "Port Wine"),
                            ("both", "Both"),
                        ],
                        help_text="Product type this search term targets.",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=100,
                        help_text="Lower number = higher priority. Terms are processed in priority order.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Only active terms are used in discovery jobs.",
                    ),
                ),
                (
                    "seasonal_start_month",
                    models.IntegerField(
                        blank=True,
                        help_text="Start month for seasonal terms (1-12). Leave blank for year-round.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "seasonal_end_month",
                    models.IntegerField(
                        blank=True,
                        help_text="End month for seasonal terms (1-12). Leave blank for year-round.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "search_count",
                    models.IntegerField(
                        default=0,
                        help_text="Number of times this term has been searched.",
                    ),
                ),
                (
                    "products_discovered",
                    models.IntegerField(
                        default=0,
                        help_text="Number of new products discovered using this term.",
                    ),
                ),
                (
                    "last_searched",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this term was last used in a search.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Search Term",
                "verbose_name_plural": "Search Terms",
                "db_table": "discovery_search_term",
                "ordering": ["priority", "-products_discovered"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "priority"],
                        name="discovery_s_is_acti_f5f33a_idx",
                    ),
                    models.Index(
                        fields=["category"], name="discovery_s_categor_b933c1_idx"
                    ),
                    models.Index(
                        fields=["product_type"], name="discovery_s_product_8dcc82_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DiscoveryResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_url", models.URLField(help_text="URL that was crawled.")),
                (
                    "source_domain",
                    models.CharField(
                        help_text="Domain of the source URL.", max_length=100
                    ),
                ),
                (
                    "source_title",
                    models.CharField(
                        blank=True,
                        help_text="Title from search results.",
                        max_length=500,
                    ),
                ),
                (
                    "search_rank",
                    models.IntegerField(
                        help_text="Position in search results (1 = first)."
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of product found, if any.",
                        max_length=200,
                    ),
                ),
                (
                    "is_new_product",
                    models.BooleanField(
                        default=False, help_text="Whether this was a new product."
                    ),
                ),
                (
                    "crawl_success",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the URL was successfully crawled.",
                    ),
                ),
                (
                    "extraction_success",
                    models.BooleanField(
                        default=False, help_text="Whether product extraction succeeded."
                    ),
                ),
                (
                    "is_duplicate",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was identified as a duplicate.",
                    ),
                ),
                (
                    "needs_review",
                    models.BooleanField(
                        default=False, help_text="Whether this needs human review."
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if crawl/extraction failed.",
                    ),
                ),
                (
                    "final_source_url",
                    models.URLField(
                        blank=True,
                        help_text="Final URL used after SmartCrawler fallback.",
                        null=True,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        blank=True,
                        help_text="Source type: primary, official_brand, trusted_retailer, other.",
                        max_length=50,
                    ),
                ),
                (
                    "name_match_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Name similarity score from SmartCrawler.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        help_text="The job this result belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="crawler.discoveryjob",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="The product discovered, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discovery_results",
                        to="crawler.discoveredproduct",
                    ),
                ),
                (
                    "search_term",
                    models.ForeignKey(
                        help_text="The search term that found this result.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="crawler.searchterm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Discovery Result",
                "verbose_name_plural": "Discovery Results",
                "db_table": "discovery_result",
                "ordering": ["job", "search_rank"],
            },
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(fields=["status"], name="discovery_j_status_4caba2_idx"),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(
                fields=["started_at"], name="discovery_j_started_182e73_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(
                fields=["schedule", "started_at"], name="discovery_j_schedul_d7a44c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryresult",
            index=models.Index(
                fields=["job", "is_new_product"], name="discovery_r_job_id_7b381f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryresult",
            index=models.Index(
                fields=["source_domain"], name="discovery_r_source__04236d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryresult",
            index=models.Index(
                fields=["needs_review"], name="discovery_r_needs_r_b3cada_idx"
            ),
        ),
    ]
