# Generated by Django 5.2.8 on 2026-01-01 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0022_discovery_result_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuotaUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_name",
                    models.CharField(
                        help_text="Name of the API (serpapi, scrapingbee, ai_service).",
                        max_length=50,
                    ),
                ),
                (
                    "month",
                    models.CharField(
                        help_text="Month key in YYYY-MM format.", max_length=7
                    ),
                ),
                (
                    "current_usage",
                    models.IntegerField(
                        default=0, help_text="Number of API calls used this month."
                    ),
                ),
                (
                    "monthly_limit",
                    models.IntegerField(
                        default=1000, help_text="Maximum calls allowed this month."
                    ),
                ),
                (
                    "last_used",
                    models.DateTimeField(
                        blank=True, help_text="When the API was last called.", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Quota Usage",
                "verbose_name_plural": "Quota Usage",
                "db_table": "quota_usage",
                "ordering": ["-month", "api_name"],
                "unique_together": {("api_name", "month")},
            },
        ),
    ]
