# Generated by Django 5.2.8 on 2026-01-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0024_unified_crawl_schedule"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="crawlschedule",
            new_name="crawl_sched_is_acti_208d17_idx",
            old_name="crawl_sched_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="crawlschedule",
            new_name="crawl_sched_categor_7434e0_idx",
            old_name="crawl_sched_categor_idx",
        ),
        migrations.AddField(
            model_name="crawljob",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="crawler.crawlschedule",
            ),
        ),
        migrations.AlterField(
            model_name="crawljob",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crawl_jobs",
                to="crawler.crawlersource",
            ),
        ),
        migrations.AlterField(
            model_name="crawlschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="discoveryschedule",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("hourly", "Hourly"),
                    ("every_6_hours", "Every 6 Hours"),
                    ("every_12_hours", "Every 12 Hours"),
                    ("daily", "Daily"),
                    ("weekly", "Weekly"),
                    ("biweekly", "Bi-weekly"),
                    ("monthly", "Monthly"),
                    ("quarterly", "Quarterly"),
                ],
                help_text="How often to run this schedule.",
                max_length=20,
            ),
        ),
    ]
