# Generated by Django 5.2.8 on 2026-01-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0025_crawljob_schedule_fk"),
    ]

    operations = [
        # First remove the old schedule FK from DiscoveryJob
        migrations.RemoveField(
            model_name="discoveryjob",
            name="schedule",
        ),
        # Then delete DiscoverySchedule model
        migrations.DeleteModel(
            name="DiscoverySchedule",
        ),
        # Now add the new crawl_schedule FK and index
        migrations.AddField(
            model_name="discoveryjob",
            name="crawl_schedule",
            field=models.ForeignKey(
                blank=True,
                help_text="The unified schedule that triggered this job, if any.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="discovery_jobs",
                to="crawler.crawlschedule",
            ),
        ),
        migrations.AddIndex(
            model_name="discoveryjob",
            index=models.Index(
                fields=["crawl_schedule", "started_at"],
                name="discovery_j_crawl_s_da0760_idx",
            ),
        ),
    ]
