# Generated by Django 5.2.8 on 2026-01-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0026_unified_scheduling_cleanup"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="categoryinsight",
            name="unique_category_insight",
        ),
        # Removed: migrations.RemoveIndex for discovery_j_schedul_d7a44c_idx
        # Index doesn't exist in current database state
        migrations.AddConstraint(
            model_name="categoryinsight",
            constraint=models.UniqueConstraint(
                fields=("product_type", "sub_category", "region", "country"),
                name="unique_category_insight",
            ),
        ),
    ]
