# Generated by Django 5.2.8 on 2026-01-04 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0029_fix_schema_mismatches"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["-is_primary"],
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.AlterModelOptions(
            name="productrating",
            options={
                "ordering": ["-score"],
                "verbose_name": "Product Rating",
                "verbose_name_plural": "Product Ratings",
            },
        ),
        migrations.AlterField(
            model_name="brandsource",
            name="brand",
            field=models.ForeignKey(
                help_text="The brand",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sources",
                to="crawler.discoveredbrand",
            ),
        ),
        migrations.AlterField(
            model_name="brandsource",
            name="extraction_confidence",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Confidence score for extraction (0.0-1.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="brandsource",
            name="mention_count",
            field=models.IntegerField(
                default=1, help_text="Number of times mentioned in this source"
            ),
        ),
        migrations.AlterField(
            model_name="brandsource",
            name="mention_type",
            field=models.CharField(
                blank=True, help_text="Type of mention", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="brandsource",
            name="source",
            field=models.ForeignKey(
                help_text="The source that mentioned this brand",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brands",
                to="crawler.crawledsource",
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="aging_vessel",
            field=models.CharField(
                blank=True,
                help_text="Type of vessel used for aging",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="bottling_year",
            field=models.IntegerField(
                blank=True, help_text="Year of bottling", null=True
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="decanting_required",
            field=models.BooleanField(
                default=False, help_text="Whether decanting is recommended"
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="douro_subregion",
            field=models.CharField(
                blank=True,
                choices=[
                    ("baixo_corgo", "Baixo Corgo"),
                    ("cima_corgo", "Cima Corgo"),
                    ("douro_superior", "Douro Superior"),
                ],
                help_text="Douro subregion",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="drinking_window",
            field=models.CharField(
                blank=True,
                help_text="Optimal drinking window (e.g., '2025-2060')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="grape_varieties",
            field=models.JSONField(
                blank=True, default=list, help_text="Grape varieties used"
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="harvest_year",
            field=models.IntegerField(
                blank=True, help_text="Year of harvest/vintage", null=True
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="indication_age",
            field=models.CharField(
                blank=True,
                help_text="Age indication (e.g., '20 Year', '10 Year')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="producer_house",
            field=models.CharField(
                help_text="Port house/producer name", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="quinta",
            field=models.CharField(
                blank=True, help_text="Quinta (estate) name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="style",
            field=models.CharField(
                choices=[
                    ("ruby", "Ruby"),
                    ("tawny", "Tawny"),
                    ("white", "White"),
                    ("rose", "Rose"),
                    ("lbv", "Late Bottled Vintage (LBV)"),
                    ("vintage", "Vintage"),
                    ("colheita", "Colheita"),
                    ("crusted", "Crusted"),
                    ("single_quinta", "Single Quinta"),
                    ("garrafeira", "Garrafeira"),
                ],
                help_text="Port wine style",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="height",
            field=models.IntegerField(
                blank=True, help_text="Image height in pixels", null=True
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("bottle", "Bottle"),
                    ("label", "Label"),
                    ("packaging", "Packaging"),
                    ("lifestyle", "Lifestyle"),
                ],
                help_text="Type of image",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Whether this is the primary image"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                help_text="The product this image belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images_rel",
                to="crawler.discoveredproduct",
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="source",
            field=models.CharField(help_text="Source of the image", max_length=200),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="url",
            field=models.URLField(help_text="URL to the image"),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="width",
            field=models.IntegerField(
                blank=True, help_text="Image width in pixels", null=True
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="date",
            field=models.DateField(
                blank=True, help_text="Date of the rating", null=True
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="max_score",
            field=models.IntegerField(
                help_text="Maximum possible score (e.g., 100, 5)"
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="product",
            field=models.ForeignKey(
                help_text="The product this rating is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings_rel",
                to="crawler.discoveredproduct",
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="review_count",
            field=models.IntegerField(
                blank=True,
                help_text="Number of reviews (for aggregate scores)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="review_url",
            field=models.URLField(
                blank=True, help_text="URL to full review", null=True
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="reviewer",
            field=models.CharField(
                blank=True, help_text="Reviewer name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="score",
            field=models.DecimalField(
                decimal_places=2, help_text="Rating score", max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="source",
            field=models.CharField(
                help_text="Rating source/platform name", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="productrating",
            name="source_country",
            field=models.CharField(
                blank=True,
                help_text="Country of the rating source",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productsource",
            name="extraction_confidence",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Confidence score for extraction (0.0-1.0)",
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="productsource",
            name="fields_extracted",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of field names extracted from this source",
            ),
        ),
        migrations.AlterField(
            model_name="productsource",
            name="mention_count",
            field=models.IntegerField(
                default=1, help_text="Number of times mentioned in this source"
            ),
        ),
        migrations.AlterField(
            model_name="productsource",
            name="mention_type",
            field=models.CharField(
                blank=True, help_text="Type of mention", max_length=20, null=True
            ),
        ),
        migrations.AlterField(
            model_name="productsource",
            name="product",
            field=models.ForeignKey(
                help_text="The product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_sources",
                to="crawler.discoveredproduct",
            ),
        ),
        migrations.AlterField(
            model_name="productsource",
            name="source",
            field=models.ForeignKey(
                help_text="The source that mentioned this product",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="crawler.crawledsource",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="brandsource",
            unique_together={("brand", "source")},
        ),
        migrations.AlterUniqueTogether(
            name="productsource",
            unique_together={("product", "source")},
        ),
        migrations.AddIndex(
            model_name="brandsource",
            index=models.Index(fields=["brand"], name="brand_sourc_brand_i_a2383c_idx"),
        ),
        migrations.AddIndex(
            model_name="brandsource",
            index=models.Index(
                fields=["source"], name="brand_sourc_source__32b417_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["product"], name="product_ima_product_11eb72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productrating",
            index=models.Index(
                fields=["product", "source"], name="product_rat_product_134f14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=["product"], name="product_sou_product_66765d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productsource",
            index=models.Index(
                fields=["source"], name="product_sou_source__d763fb_idx"
            ),
        ),
    ]
