# Generated by Django 5.2.8 on 2026-01-04 15:51

from django.db import migrations


class Migration(migrations.Migration):
    """
    This migration is now a no-op.

    The original migration tried to align SourceMetrics and AlertRule models,
    but those models are already correctly defined in migrations 0012 and 0013.

    This migration is kept for migration history consistency.
    """

    dependencies = [
        ("crawler", "0031_fix_table_names_and_create_missing"),
    ]

    operations = [
        # All operations removed - models are already correct from 0012 and 0013
    ]
