# Generated by Django 5.2.8 on 2026-01-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0032_final_alignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="best_price_updated",
            field=models.DateTimeField(
                blank=True, help_text="When the best price was last updated", null=True
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="finish_description",
            field=models.TextField(
                blank=True,
                help_text="Overall finish description combining length, warmth, and lingering notes",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="palate_description",
            field=models.TextField(
                blank=True,
                help_text="Overall palate description combining initial taste, evolution, and mouthfeel",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="source_count",
            field=models.IntegerField(
                default=1,
                help_text="Number of unique sources this product data was collected from",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="verified_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Fields verified by multiple sources: ['name', 'abv', 'palate_description']",
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="status",
            field=models.CharField(
                choices=[
                    ("incomplete", "Incomplete"),
                    ("partial", "Partial"),
                    ("complete", "Complete"),
                    ("verified", "Verified"),
                    ("rejected", "Rejected"),
                    ("merged", "Merged"),
                    ("pending", "Pending Review (Legacy)"),
                    ("approved", "Approved (Legacy)"),
                    ("duplicate", "Duplicate (Legacy)"),
                    ("skeleton", "Skeleton (Legacy)"),
                ],
                default="incomplete",
                help_text="Product status: incomplete, partial, complete, verified, rejected, merged",
                max_length=20,
            ),
        ),
    ]
