# Generated by Django 5.2.8 on 2026-01-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0034_migrate_data_to_new_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFingerprint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source identifier (e.g., 'iwsc', 'sfwsc').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        help_text="SHA-256 hash of page structure elements.",
                        max_length=64,
                    ),
                ),
                (
                    "sample_url",
                    models.URLField(help_text="URL used to generate the fingerprint."),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When the fingerprint was last updated.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Fingerprint",
                "verbose_name_plural": "Source Fingerprints",
                "db_table": "source_fingerprint",
            },
        ),
        migrations.CreateModel(
            name="APICrawlJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique job identifier (UUID).",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source identifier (e.g., 'iwsc', 'sfwsc').",
                        max_length=50,
                    ),
                ),
                ("year", models.IntegerField(help_text="Competition year to crawl.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        help_text="Current job status.",
                        max_length=20,
                    ),
                ),
                (
                    "progress",
                    models.JSONField(
                        default=dict,
                        help_text="Progress details: {total, processed, errors}.",
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error message if job failed.", null=True
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for background processing.",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the job started execution.",
                        null=True,
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the job completed.", null=True
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the job was created."
                    ),
                ),
            ],
            options={
                "verbose_name": "API Crawl Job",
                "verbose_name_plural": "API Crawl Jobs",
                "db_table": "api_crawl_job",
                "indexes": [
                    models.Index(
                        fields=["status"], name="api_crawl_j_status_e1f7b2_idx"
                    ),
                    models.Index(
                        fields=["source", "year"], name="api_crawl_j_source_495a44_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceHealthCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source identifier (e.g., 'iwsc', 'sfwsc').",
                        max_length=50,
                    ),
                ),
                (
                    "check_type",
                    models.CharField(
                        choices=[
                            ("selector", "Selector Health"),
                            ("yield", "Yield Monitoring"),
                            ("fingerprint", "Structural Fingerprint"),
                            ("known_product", "Known Product Verification"),
                        ],
                        help_text="Type of health check performed.",
                        max_length=20,
                    ),
                ),
                (
                    "is_healthy",
                    models.BooleanField(help_text="Whether the health check passed."),
                ),
                (
                    "details",
                    models.JSONField(
                        default=dict,
                        help_text="Detailed health check results and metrics.",
                    ),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When the health check was performed.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source Health Check",
                "verbose_name_plural": "Source Health Checks",
                "db_table": "source_health_check",
                "indexes": [
                    models.Index(
                        fields=["source", "check_type"],
                        name="source_heal_source_b6e4df_idx",
                    ),
                    models.Index(
                        fields=["checked_at"], name="source_heal_checked_5e7343_idx"
                    ),
                ],
            },
        ),
    ]
