# Generated by Django 5.2.8 on 2026-01-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0035_add_health_and_api_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="discoveredproduct",
            name="enriched_data",
        ),
        migrations.RemoveField(
            model_name="discoveredproduct",
            name="extracted_data",
        ),
        migrations.RemoveField(
            model_name="discoveredproduct",
            name="taste_profile",
        ),
        migrations.RemoveField(
            model_name="whiskeydetails",
            name="cask_finish",
        ),
        migrations.RemoveField(
            model_name="whiskeydetails",
            name="cask_type",
        ),
        migrations.RemoveField(
            model_name="whiskeydetails",
            name="chill_filtered",
        ),
        migrations.RemoveField(
            model_name="whiskeydetails",
            name="color_added",
        ),
        migrations.RemoveField(
            model_name="whiskeydetails",
            name="whiskey_country",
        ),
        migrations.RemoveField(
            model_name="whiskeydetails",
            name="whiskey_region",
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="description",
            field=models.TextField(
                blank=True, help_text="Product description", null=True
            ),
        ),
        migrations.AddField(
            model_name="whiskeydetails",
            name="natural_color",
            field=models.BooleanField(
                blank=True,
                help_text="No E150a color added (True = natural color)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="whiskeydetails",
            name="non_chill_filtered",
            field=models.BooleanField(
                blank=True, help_text="Non-chill filtered (True = NCF)", null=True
            ),
        ),
        migrations.AddField(
            model_name="whiskeydetails",
            name="peat_ppm",
            field=models.IntegerField(
                blank=True, help_text="Phenol PPM measurement for peat level", null=True
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="abv",
            field=models.DecimalField(
                blank=True,
                db_index=True,
                decimal_places=1,
                help_text="Alcohol by volume percentage 0-80%",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="age_statement",
            field=models.CharField(
                blank=True,
                help_text="Age statement (e.g., '12', '18', 'NAS')",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="country",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Country of origin",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="extraction_confidence",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Extraction confidence 0.00-1.00",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="fingerprint",
            field=models.CharField(
                db_index=True,
                help_text="Hash for deduplication - must be unique per spec",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="name",
            field=models.CharField(
                db_index=True,
                help_text="Product name - indexed per spec",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="discoveredproduct",
            name="region",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Product region (e.g., Speyside, Kentucky)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="harvest_year",
            field=models.IntegerField(
                blank=True,
                db_index=True,
                help_text="Year of harvest/vintage - indexed per spec",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="producer_house",
            field=models.CharField(
                db_index=True,
                help_text="Port house/producer name - indexed per spec",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="portwinedetails",
            name="style",
            field=models.CharField(
                choices=[
                    ("ruby", "Ruby"),
                    ("tawny", "Tawny"),
                    ("white", "White"),
                    ("rose", "Rose"),
                    ("lbv", "Late Bottled Vintage (LBV)"),
                    ("vintage", "Vintage"),
                    ("colheita", "Colheita"),
                    ("crusted", "Crusted"),
                    ("single_quinta", "Single Quinta"),
                    ("garrafeira", "Garrafeira"),
                ],
                help_text="Port wine style: ruby, tawny, vintage, LBV, etc.",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="whiskeydetails",
            name="distillery",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Distillery name - indexed per spec",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="whiskeydetails",
            name="peat_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("unpeated", "Unpeated"),
                    ("lightly_peated", "Lightly Peated"),
                    ("medium_peated", "Medium Peated"),
                    ("heavily_peated", "Heavily Peated"),
                ],
                help_text="Level of peat: unpeated, lightly, heavily",
                max_length=20,
                null=True,
            ),
        ),
    ]
