# Generated by Django 5.2.8 on 2026-01-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0036_remove_discoveredproduct_enriched_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlschedule",
            name="enrich",
            field=models.BooleanField(
                default=False,
                help_text="Run verification pipeline on extracted products",
            ),
        ),
        migrations.AddField(
            model_name="crawlschedule",
            name="total_products_verified",
            field=models.IntegerField(default=0),
        ),
    ]
