# Generated by Django 5.2.8 on 2026-01-09 13:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0037_add_schedule_enrich_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductTypeConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_type",
                    models.CharField(
                        db_index=True,
                        help_text="Product type identifier (e.g., 'whiskey', 'port_wine')",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for display", max_length=100
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        default="1.0",
                        help_text="Configuration version for tracking changes",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable this product type configuration",
                    ),
                ),
                (
                    "categories",
                    models.JSONField(
                        default=list,
                        help_text='Valid categories: ["bourbon", "scotch", "rye"]',
                    ),
                ),
                (
                    "max_sources_per_product",
                    models.IntegerField(
                        default=5,
                        help_text="Maximum number of sources to fetch per product during enrichment",
                    ),
                ),
                (
                    "max_serpapi_searches",
                    models.IntegerField(
                        default=3,
                        help_text="Maximum SerpAPI searches per product (cost control)",
                    ),
                ),
                (
                    "max_enrichment_time_seconds",
                    models.IntegerField(
                        default=120,
                        help_text="Maximum time in seconds for enrichment per product",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="User who last updated this configuration",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Type Configuration",
                "verbose_name_plural": "Product Type Configurations",
                "db_table": "product_type_config",
                "ordering": ["product_type"],
            },
        ),
        migrations.CreateModel(
            name="EnrichmentConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(
                        help_text='Template identifier (e.g., "tasting_notes")',
                        max_length=50,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable template name", max_length=100
                    ),
                ),
                (
                    "search_template",
                    models.CharField(
                        help_text='Use placeholders: "{name} {brand} tasting notes review"',
                        max_length=500,
                    ),
                ),
                (
                    "target_fields",
                    models.JSONField(
                        default=list,
                        help_text='Fields this enriches: ["nose_description", "palate_description"]',
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=5,
                        help_text="1-10, higher priority = search first when fields missing",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Enable/disable this enrichment template",
                    ),
                ),
                (
                    "product_type_config",
                    models.ForeignKey(
                        help_text="Product type this enrichment config applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrichment_templates",
                        to="crawler.producttypeconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enrichment Configuration",
                "verbose_name_plural": "Enrichment Configurations",
                "db_table": "enrichment_config",
                "ordering": ["-priority"],
            },
        ),
        migrations.CreateModel(
            name="QualityGateConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "skeleton_required_fields",
                    models.JSONField(
                        default=list,
                        help_text='Must have ALL of these. Example: ["name"]',
                    ),
                ),
                (
                    "partial_required_fields",
                    models.JSONField(
                        default=list,
                        help_text='Must have ALL of these. Example: ["name", "brand"]',
                    ),
                ),
                (
                    "partial_any_of_count",
                    models.IntegerField(
                        default=2,
                        help_text="Must have at least this many from any_of_fields",
                    ),
                ),
                (
                    "partial_any_of_fields",
                    models.JSONField(
                        default=list,
                        help_text='Pool of fields. Example: ["abv", "description", "region"]',
                    ),
                ),
                (
                    "complete_required_fields",
                    models.JSONField(
                        default=list,
                        help_text='Must have ALL. Example: ["name", "brand", "description", "palate_flavors"]',
                    ),
                ),
                (
                    "complete_any_of_count",
                    models.IntegerField(
                        default=2,
                        help_text="Must have at least this many from any_of_fields",
                    ),
                ),
                (
                    "complete_any_of_fields",
                    models.JSONField(
                        default=list,
                        help_text='Pool of fields. Example: ["abv", "nose_description", "finish_description"]',
                    ),
                ),
                (
                    "enriched_required_fields",
                    models.JSONField(
                        default=list,
                        help_text="Must have ALL (inherits COMPLETE + these)",
                    ),
                ),
                (
                    "enriched_any_of_count",
                    models.IntegerField(
                        default=2,
                        help_text="Must have at least this many from any_of_fields",
                    ),
                ),
                (
                    "enriched_any_of_fields",
                    models.JSONField(
                        default=list,
                        help_text='External data fields: ["awards", "ratings", "prices"]',
                    ),
                ),
                (
                    "product_type_config",
                    models.OneToOneField(
                        help_text="Product type this quality gate applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quality_gates",
                        to="crawler.producttypeconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quality Gate Configuration",
                "verbose_name_plural": "Quality Gate Configurations",
                "db_table": "quality_gate_config",
            },
        ),
        migrations.CreateModel(
            name="FieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        db_index=True,
                        help_text="Field name used in extraction schema",
                        max_length=100,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable field name", max_length=200
                    ),
                ),
                (
                    "field_group",
                    models.CharField(
                        choices=[
                            ("core", "Core Product"),
                            ("tasting_appearance", "Tasting - Appearance"),
                            ("tasting_nose", "Tasting - Nose"),
                            ("tasting_palate", "Tasting - Palate"),
                            ("tasting_finish", "Tasting - Finish"),
                            ("tasting_overall", "Tasting - Overall"),
                            ("production", "Production"),
                            ("cask", "Cask/Maturation"),
                            ("related", "Related Data"),
                            ("type_specific", "Type Specific"),
                        ],
                        default="core",
                        help_text="Logical group for organizing fields",
                        max_length=50,
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("text", "Text (long)"),
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("boolean", "Boolean"),
                            ("array", "Array"),
                            ("object", "Object"),
                        ],
                        help_text="Data type of the field",
                        max_length=20,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        blank=True,
                        help_text="For arrays: type of items (string, object)",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Description for AI extraction - be specific and clear!"
                    ),
                ),
                (
                    "examples",
                    models.JSONField(
                        default=list,
                        help_text='Examples help AI understand: ["Ardbeg 10", "Glenfiddich 18"]',
                    ),
                ),
                (
                    "allowed_values",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='For enums: ["gold", "silver", "bronze"]',
                    ),
                ),
                (
                    "item_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Schema for object/array items (awards, ratings, etc.)",
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        choices=[
                            ("DiscoveredProduct", "DiscoveredProduct"),
                            ("WhiskeyDetails", "WhiskeyDetails"),
                            ("PortWineDetails", "PortWineDetails"),
                            ("ProductAward", "ProductAward"),
                            ("ProductPrice", "ProductPrice"),
                            ("ProductRating", "ProductRating"),
                        ],
                        help_text="Django model where this field is stored",
                        max_length=100,
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="Field name in the target model", max_length=100
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Order within field group (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this field definition"
                    ),
                ),
                (
                    "product_type_config",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = shared/base field for all product types",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="crawler.producttypeconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Definition",
                "verbose_name_plural": "Field Definitions",
                "db_table": "field_definition",
                "ordering": ["field_group", "sort_order", "field_name"],
                "unique_together": {("product_type_config", "field_name")},
            },
        ),
    ]
