# Generated by Django 5.2.8 on 2026-01-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0038_config_models_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawledsource",
            name="cleanup_eligible",
            field=models.BooleanField(
                default=False,
                help_text="Whether raw content can be cleared (extraction processed AND wayback saved)",
            ),
        ),
        migrations.AddField(
            model_name="crawledsource",
            name="preprocessed_at",
            field=models.DateTimeField(
                blank=True, help_text="When the content was preprocessed", null=True
            ),
        ),
        migrations.AddField(
            model_name="crawledsource",
            name="preprocessed_content",
            field=models.TextField(
                blank=True,
                help_text="Preprocessed/cleaned content for AI extraction (93% token savings)",
                null=True,
            ),
        ),
    ]
