# Generated by Django 5.2.8 on 2026-01-12 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0040_searchterm_changes_and_list_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crawledsource",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("award_page", "Award Page"),
                    ("review_article", "Review Article"),
                    ("retailer_page", "Retailer Page"),
                    ("distillery_page", "Distillery Page"),
                    ("news_article", "News Article"),
                    ("list_page", "List Page"),
                ],
                help_text="Type of crawled page: award_page, review_article, etc.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PipelineConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "max_serpapi_searches",
                    models.IntegerField(
                        default=6,
                        help_text="Maximum SerpAPI searches per product (V3: increased from 3)",
                    ),
                ),
                (
                    "max_sources_per_product",
                    models.IntegerField(
                        default=8,
                        help_text="Maximum sources to fetch per product (V3: increased from 5)",
                    ),
                ),
                (
                    "max_enrichment_time_seconds",
                    models.IntegerField(
                        default=180,
                        help_text="Maximum enrichment time in seconds (V3: increased from 120)",
                    ),
                ),
                (
                    "awards_search_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable dedicated awards search (Step 4 in V3 pipeline)",
                    ),
                ),
                (
                    "awards_search_template",
                    models.CharField(
                        default="{name} {brand} awards medals competition winner",
                        help_text="Search template for awards discovery",
                        max_length=500,
                    ),
                ),
                (
                    "members_only_detection_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Enable content analysis for members-only/paywall sites",
                    ),
                ),
                (
                    "members_only_patterns",
                    models.JSONField(
                        default=list,
                        help_text="Regex patterns to detect members-only sites (login forms, paywalls)",
                    ),
                ),
                (
                    "status_thresholds",
                    models.JSONField(
                        default=dict,
                        help_text="Status requirements per level (skeleton, partial, baseline, enriched, complete)",
                    ),
                ),
                (
                    "ecp_complete_threshold",
                    models.DecimalField(
                        decimal_places=2,
                        default=90.0,
                        help_text="ECP percentage required for COMPLETE status (V3 default: 90%)",
                        max_digits=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_type_config",
                    models.OneToOneField(
                        help_text="Product type this pipeline config applies to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pipeline_config",
                        to="crawler.producttypeconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pipeline Configuration",
                "verbose_name_plural": "Pipeline Configurations",
                "db_table": "pipeline_config",
            },
        ),
    ]
