# Generated by Django 5.2.8 on 2026-01-12 09:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0041_add_pipeline_config_v3"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group_key",
                    models.CharField(
                        help_text="Unique key for this group (e.g., 'tasting_nose', 'cask_info')",
                        max_length=50,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for display", max_length=100
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        default=list, help_text="List of field names in this group"
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(
                        default=0, help_text="Display order (lower = first)"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Enable/disable this field group"
                    ),
                ),
                (
                    "product_type_config",
                    models.ForeignKey(
                        help_text="Product type this field group belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_groups",
                        to="crawler.producttypeconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Field Group",
                "verbose_name_plural": "Field Groups",
                "db_table": "field_group",
                "ordering": ["sort_order"],
                "unique_together": {("product_type_config", "group_key")},
            },
        ),
    ]
