# Generated by Django 5.2.8 on 2026-01-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0042_add_field_group_v3"),
    ]

    operations = [
        migrations.AddField(
            model_name="qualitygateconfig",
            name="baseline_or_field_exceptions",
            field=models.JSONField(
                default=dict,
                help_text='V3: Conditions to waive OR requirements. Example: {"style": ["ruby", "reserve_ruby"]}',
            ),
        ),
        migrations.AddField(
            model_name="qualitygateconfig",
            name="baseline_or_fields",
            field=models.JSONField(
                default=list,
                help_text='V3: List of field pairs where either satisfies. Example: [["indication_age", "harvest_year"]]',
            ),
        ),
        migrations.AddField(
            model_name="qualitygateconfig",
            name="baseline_required_fields",
            field=models.JSONField(
                default=list,
                help_text="V3: Must have ALL. Replaces complete_required_fields.",
            ),
        ),
        migrations.AddField(
            model_name="qualitygateconfig",
            name="enriched_or_fields",
            field=models.JSONField(
                default=list,
                help_text='V3: List of field pairs where either satisfies. Example: [["complexity", "overall_complexity"]]',
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="complete_any_of_count",
            field=models.IntegerField(
                default=0, help_text="DEPRECATED in V3 - not used"
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="complete_any_of_fields",
            field=models.JSONField(
                default=list, help_text="DEPRECATED in V3 - not used"
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="complete_required_fields",
            field=models.JSONField(
                default=list,
                help_text="DEPRECATED in V3 - use baseline_required_fields",
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="enriched_any_of_count",
            field=models.IntegerField(
                default=0, help_text="DEPRECATED in V3 - not used"
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="enriched_any_of_fields",
            field=models.JSONField(
                default=list, help_text="DEPRECATED in V3 - not used"
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="enriched_required_fields",
            field=models.JSONField(
                default=list, help_text='V3: Must have ALL. Example: ["mouthfeel"]'
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="partial_any_of_count",
            field=models.IntegerField(
                default=0, help_text="DEPRECATED in V3 - not used"
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="partial_any_of_fields",
            field=models.JSONField(
                default=list, help_text="DEPRECATED in V3 - not used"
            ),
        ),
        migrations.AlterField(
            model_name="qualitygateconfig",
            name="partial_required_fields",
            field=models.JSONField(
                default=list,
                help_text='Must have ALL. V3: ["name", "brand", "abv", "region", "country", "category"]',
            ),
        ),
    ]
