# Generated by Django 5.2.8 on 2026-01-12 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0043_quality_gate_config_v3"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="awards_search_completed",
            field=models.BooleanField(
                default=False,
                help_text="V3: Whether dedicated awards search (Step 4) was performed",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="ecp_total",
            field=models.DecimalField(
                db_index=True,
                decimal_places=2,
                default=0,
                help_text="V3: Total ECP percentage (0-100). 90%+ = COMPLETE status",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="enrichment_completion",
            field=models.JSONField(
                default=dict,
                help_text="V3: ECP by field group with missing field lists",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="members_only_sites_detected",
            field=models.JSONField(
                default=list,
                help_text="V3: URLs detected as members-only/paywall during enrichment",
            ),
        ),
    ]
