# Generated by Django 5.2.8 on 2026-01-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0044_discovered_product_ecp_v3"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddefinition",
            name="derive_from",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Field name to derive this array field from (e.g., 'finish_flavors' derives from 'finish_description'). When set, AI will extract individual items from the prose description.",
                max_length=100,
            ),
        ),
    ]
