# Generated by Django 5.2.8 on 2026-01-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0045_add_derive_from_to_fielddefinition"),
    ]

    operations = [
        migrations.AddField(
            model_name="discoveredproduct",
            name="enrichment_sources_rejected",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="V3: URLs rejected during enrichment with reasons [{url, reason, timestamp}]",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="enrichment_sources_searched",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="V3: All URLs searched/attempted during enrichment",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="enrichment_sources_used",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="V3: URLs that successfully contributed data during enrichment",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="enrichment_steps_completed",
            field=models.IntegerField(
                default=0,
                help_text="V3: Number of enrichment steps completed (0-2 for generic search)",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="field_provenance",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="V3: Mapping of field_name -> source_url for audit trail",
            ),
        ),
        migrations.AddField(
            model_name="discoveredproduct",
            name="last_enrichment_at",
            field=models.DateTimeField(
                blank=True,
                help_text="V3: Timestamp of last enrichment attempt",
                null=True,
            ),
        ),
    ]
