# Generated by Django 5.2.8 on 2026-01-13 20:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0046_add_enrichment_source_tracking"),
    ]

    operations = [
        migrations.AddField(
            model_name="producttypeconfig",
            name="awards_search_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable dedicated awards search (Step 4 in V3 pipeline)",
            ),
        ),
        migrations.AddField(
            model_name="producttypeconfig",
            name="awards_search_template",
            field=models.CharField(
                default="{name} {brand} awards medals competition winner",
                help_text="Search template for awards discovery",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="producttypeconfig",
            name="ecp_complete_threshold",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("90.0"),
                help_text="ECP percentage required for COMPLETE status (V3 default: 90%)",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="producttypeconfig",
            name="members_only_detection_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Enable content analysis for members-only/paywall sites",
            ),
        ),
        migrations.AddField(
            model_name="producttypeconfig",
            name="members_only_patterns",
            field=models.JSONField(
                default=list,
                help_text="Regex patterns to detect members-only sites (login forms, paywalls)",
            ),
        ),
        migrations.AddField(
            model_name="producttypeconfig",
            name="status_thresholds",
            field=models.JSONField(
                default=dict,
                help_text="Status requirements per level (skeleton, partial, baseline, enriched, complete)",
            ),
        ),
        migrations.AlterField(
            model_name="producttypeconfig",
            name="max_enrichment_time_seconds",
            field=models.IntegerField(
                default=180,
                help_text="Maximum time in seconds for enrichment per product (V3: increased from 120)",
            ),
        ),
        migrations.AlterField(
            model_name="producttypeconfig",
            name="max_serpapi_searches",
            field=models.IntegerField(
                default=6,
                help_text="Maximum SerpAPI searches per product (V3: increased from 3)",
            ),
        ),
        migrations.AlterField(
            model_name="producttypeconfig",
            name="max_sources_per_product",
            field=models.IntegerField(
                default=8,
                help_text="Maximum number of sources to fetch per product during enrichment (V3: increased from 5)",
            ),
        ),
    ]
