# Generated by Django - Data Migration for Config Consolidation (Task 0.2)

from django.db import migrations


def migrate_pipeline_config_data(apps, schema_editor):
    """
    Migrate data from PipelineConfig to ProductTypeConfig.

    This copies V3 fields from PipelineConfig to the parent ProductTypeConfig,
    as part of the config consolidation effort (Task 0.2).
    """
    PipelineConfig = apps.get_model("crawler", "PipelineConfig")
    ProductTypeConfig = apps.get_model("crawler", "ProductTypeConfig")

    migrated_count = 0

    for pipeline_config in PipelineConfig.objects.select_related("product_type_config").all():
        ptc = pipeline_config.product_type_config

        # Copy all V3 fields from PipelineConfig to ProductTypeConfig
        ptc.max_serpapi_searches = pipeline_config.max_serpapi_searches
        ptc.max_sources_per_product = pipeline_config.max_sources_per_product
        ptc.max_enrichment_time_seconds = pipeline_config.max_enrichment_time_seconds
        ptc.awards_search_enabled = pipeline_config.awards_search_enabled
        ptc.awards_search_template = pipeline_config.awards_search_template
        ptc.members_only_detection_enabled = pipeline_config.members_only_detection_enabled
        ptc.members_only_patterns = pipeline_config.members_only_patterns
        ptc.status_thresholds = pipeline_config.status_thresholds
        ptc.ecp_complete_threshold = pipeline_config.ecp_complete_threshold

        ptc.save()
        migrated_count += 1

    print(f"Migrated {migrated_count} PipelineConfig records to ProductTypeConfig")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration - no action needed as PipelineConfig still exists.
    The data in ProductTypeConfig can remain as it doesn't break anything.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("crawler", "0047_add_v3_fields_to_product_type_config"),
    ]

    operations = [
        migrations.RunPython(migrate_pipeline_config_data, reverse_migration),
    ]
