# Generated by Django 5.2.8 on 2026-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0048_migrate_pipeline_config_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddefinition",
            name="format_hint",
            field=models.TextField(
                blank=True,
                help_text="Format specification for AI extraction (e.g., 'YYYY-YYYY for date ranges')",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producttypeconfig",
            name="max_enrichment_time_seconds",
            field=models.IntegerField(
                default=180,
                help_text="Maximum enrichment time in seconds (V3: increased from 120)",
            ),
        ),
        migrations.AlterField(
            model_name="producttypeconfig",
            name="max_sources_per_product",
            field=models.IntegerField(
                default=8,
                help_text="Maximum sources to fetch per product (V3: increased from 5)",
            ),
        ),
    ]
