# Generated by Django 5.2.8 on 2026-01-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawler", "0049_add_format_hint_to_field_definition"),
    ]

    operations = [
        migrations.AddField(
            model_name="crawlersource",
            name="manual_tier_override",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Tier 1 - httpx"),
                    (2, "Tier 2 - Playwright"),
                    (3, "Tier 3 - ScrapingBee"),
                ],
                help_text="Force specific tier for this source (overrides adaptive selection)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="crawlersource",
            name="manual_timeout_override",
            field=models.IntegerField(
                blank=True,
                help_text="Force specific timeout in milliseconds for this source",
                null=True,
            ),
        ),
    ]
